### ISSUE TITLE
Simulation FPS ?

### ISSUE THREAD

**Issue by yiwc** [allenai/ai2thor#1020]
Dear Team,

Thanks for this great work.

May I know what's the simulation FPS frame per second? lets say on single GPU.

**Comment by roozbehm** [comment]
FPS depends on a lot of parameters such as the resolution of the rendered images, the quality of rendering, number of processes that are run simultaneously, whether physics simulation is enabled or not, the quality of the physics simulation, whether the robot arm is used or not, etc. So it is not possible to report a single FPS number since that is only valid for a specific configuration. The following blogpost includes some FPS numbers for some specific configurations that you can use as reference (however they include the time of the forward pass of the neural network as well). [https://blog.allenai.org/ai2-thor-partners-with-unity-to-enable-headless-multi-node-training-in-the-cloud-571802be5ad3](https://blog.allenai.org/ai2-thor-partners-with-unity-to-enable-headless-multi-node-training-in-the-cloud-571802be5ad3)

**Comment by yiwc** [comment]
Thanks Yes this blog helps exactly

> FPS depends on a lot of parameters such as the resolution of the rendered images, the quality of rendering, number of processes that are run simultaneously, whether physics simulation is enabled or not, the quality of the physics simulation, whether the robot arm is used or not, etc. So it is not possible to report a single FPS number since that is only valid for a specific configuration. The following blogpost includes some FPS numbers for some specific configurations that you can use as reference (however they include the time of the forward pass of the neural network as well). [https://blog.allenai.org/ai2-thor-partners-with-unity-to-enable-headless-multi-node-training-in-the-cloud-571802be5ad3](https://blog.allenai.org/ai2-thor-partners-with-unity-to-enable-headless-multi-node-training-in-the-cloud-571802be5ad3)
