### ISSUE TITLE
Object Position and Coordinates Documentation 

### ISSUE THREAD

**Issue by aishwaryap** [allenai/ai2thor#1047]
Hi,

Is there documentation anywhere on what is the difference between the properties `axisAlignedBoundingBox` and `objectOrientedBoundingBox` of an object? I've examined them for some objects and they seem to be close but not exactly identical. I have also noticed that `objectOrientedBoundingBox` only seems to be available for `moveable` objects.
Also, for an object `obj`, I've noticed that `obj['axisAlignedBoundingBox']['center']` is close to `obj['position']` but not identical. What is the relationship between them supposed to be? 
Also, I believe x and z axes are along the floor and y is vertical but where is (0, 0, 0)? Specifically, I'm surprised to see negative coordinate values.
In case it's relevant, I am using `ai2thor` 3.1.0.

Thanks,
Aishwarya

**Comment by winthos** [comment]
The difference between an `axisAlignedBoundingBox` and an `objectOrientedBoundingBox` is that the object oriented one is always constant relative to the rotation of the object, where the axis aligned bounds is always aligned to the world axes of a scene. This is detailed in the [documentation about the axisAlignedBoundingBox](https://ai2thor.allenai.org/ithor/documentation/environment-state/#object-metadata-axisalignedboundingbox) and the [documentation about the objectOrientedBoundingBox respectively.](https://ai2thor.allenai.org/ithor/documentation/environment-state/#object-metadata-objectorientedboundingbox)

For a more visual example, please take a look at the following images taken from within the Unity editor. This first image is an example of the `objectOrientedBoundingBox` of this `bread` object at various rotations. No matter how the bread is rotated, the object oriented bounds are constant because the orientation of those bounds are relative to the local space of the bread object itself. Note the scene's global coordinate axes are reflected in the top right corner of these images as well.

**Object Oriented Bounds**
![objectorientedbounds](https://user-images.githubusercontent.com/17502636/181102867-837453b6-91b0-4cde-a80b-6e8fe987cee7.jpg)
![objectorientedbounds2](https://user-images.githubusercontent.com/17502636/181102876-f2f3040e-d62f-4e4f-b69d-dea40e6922d1.jpg)

Next, this is an example of the `axisAlignedBoundingBox` of this same bread object. This is the smallest box that encompasses the entirety of the bread, but aligned to the world axes (again see the top right for the world axes). Because the bread is rotated and not lined up with the world axes, the axis aligned bounds are bigger than the object oriented because these world axis aligned bounds must stay aligned relative to the world coordinate space rather than object relative. Note how the axes of the bounding boxes visualized here are in line with the world axes.

**Axis Aligned Bounds**
![axisalignedbounds](https://user-images.githubusercontent.com/17502636/181103233-4f895c6d-6e68-47b1-97a5-4b5542b35965.jpg)
![axisalignedbounds2](https://user-images.githubusercontent.com/17502636/181103244-9454a125-05e0-4efe-9548-fe2e33fcd770.jpg)

Currently `objectOrientedBounds` are only available for moveable objects, as all static, not moveable sim object types cannot be rotated or repositioned by default, and thus their object oriented bounds and axis aligned bounds would be the same, since they never change position. Moveable objects support object aligned bounds because of the fact that they are moveable and can have their bounds change if they only reported back axis aligned bounds, so the `objectOrientedBounds` was added so that there is a constant value that can be used for things like volume estimation.

Additionally, the center of the object bounds is the center of the box, which because of our various different sizes of sim objects, is not always the same as the object's `position` value. The position of the object is the pivot point at which that object can be manipulated, and while they are often similar as you have observed, they are distinctly different than the center of the bounding box, which is always going to be the average center of the box drawn. This is because some of our objects require agents to grab them and manipulate them about a different "pivot point" than the average center of the object. A good example of this is, if the agent were to pick up a knife, rotating the knife would make most sense if the point of rotation (the pivot point) was about the handle of the knife, not the middle average of the knife which would be where the blade is.

**Comment by aishwaryap** [comment]
Thanks!
