### ISSUE TITLE
Placing Knife in Fridge

### ISSUE THREAD

**Issue by RishiHazra** [allenai/ai2thor#1066]
Hi,

I keep noticing that the agent places the Knife, and Butterknife in the Fridge, although, from the documentation, it seems the Fridge is not a default receptacle. This is undesirable and I wonder if it is a bug in the code and if so -- how can I make this minor adjustment? I checked the controller.py code but couldn't find anything aside from what is already there in the documentation.

I'm using version 4.2.0

**Comment by winthos** [comment]
Hello!

There are a few things to consider on how the agent may be placing Knife and Butterknife typed sim objects in a Fridge. 

First is, if you are passing in `forceAction=True` to any calls to the `PutObject` action, this will, automatically bypass the placement restrictions and allow any object to be attempted to be placed in any receptacle regardless of those documented restrictions.

Additionally, if you are doing any other types of object repositioning or rearrangement, like the `InitialRandomSpawn` action to shuffle objects around, it is possible you are getting a configuration that has the knife objects placed in the fridge via that shuffling.

The controller.py code isn't what is actually executing the object manipulation actions, as that is done within the unity backend which is called via actions from the python controller, so that may be why you've hit a dead end looking into the controller.py code.

If you could provide code snippets of exactly what actions you are calling, as well as how you are initializing your scenes so we can replicate what you are seeing happen, I can look more into how this behavior could be happening to ensure there are no bugs on the Unity backend.

**Comment by RishiHazra** [comment]
```
First is, if you are passing in forceAction=True to any calls to the PutObject action, this will, automatically bypass the placement restrictions and allow any object to be attempted to be placed in any receptacle regardless of those documented restrictions.
```
I wasn't aware that forceAction=True overrules the object affordances. Thanks, it's fixed now. Will go ahead and close this issue.
