### ISSUE TITLE
Collision detection, is it possible?

### ISSUE THREAD

**Issue by edugm94** [allenai/ai2thor#111]
Hello to all,

I have a question regarding to detect collisions while navigation in the environment. I check the metadata and I saw a variable called "collided" which is always set to False, even when I try to execute "MoveAhead" command while the agent looks towards a wall (I was expecting it to turn into True, but I does not). My question is: is there any possibility to know whether the agent collides with any object?

Thanks in advance :)

**Comment by winthos** [comment]
Hello!

If you can find the BaseFPSAgentController.cs script in ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs, make an addition right around line 489 so that the if check there looks like this:

`			if (!collisionsInAction.Contains(hit.gameObject.name))
			{
				Debug.Log("Collided with " + hit.gameObject.name);
				collisionsInAction.Add(hit.gameObject.name);
				collidedObjects = collisionsInAction.ToArray();
			}
`

That should allow the collision metadata to be updated correctly.

**Comment by edugm94** [comment]
Hello,

I am using ai2thor in a virtual environment. The installation of the framework was through the command: "pip install ai2thor", and follow the instructions of the tutorial. I did not download any code. Where can I find this file then: ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs.
Thanks in advance!

**Comment by edugm94** [comment]
Hello,

I added that line of code, but the collision metadata still not updated. Could you help me, please?
Thanks in advance! :)

**Comment by Lucaweihs** [comment]
Hi edugm94,

The following worked for me:
1. Checkout the master branch (so undo the above modification).
2. Apply the following patch: [patch.txt](https://github.com/allenai/ai2thor/files/2901867/patch.txt). I.e. run `git apply PATH/TO/THE/FILE/patch.txt` from within the ai2thor directory.
3. Build THOR: i.e. run `invoke local-build`
4. Be sure to actually run your local build when starting THOR, e.g.
```
import ai2thor.controller
from ai2thor.controller import Controller
c = Controller()
c.local_executable_path = "/PATH/TO/THOR/ai2thor/unity/builds/thor-local-OSXIntel64.app/Contents/MacOS/thor-local-OSXIntel64"
c.start()
```
Note that you should be replacing all the capital words in the above paths to the appropriate directories for your computer. If you're running linux then you'll instead want to run `invoke local-build --arch Linux64` and you'll need to change the `local_executable_path` appropriately.

**Comment by edugm94** [comment]
Hi @Lucaweihs,
how can I build THOR in Linux? I've tried to find any guide but I did not find any.

Thanks!

**Comment by Lucaweihs** [comment]
Hi edugm94,

Open the `tasks.py` file and change

```
@task
def local_build(context, prefix='local'):
    arch = 'OSXIntel64'
    build_name = "builds/thor-%s-%s" % (prefix, arch)
    fetch_source_textures(context)
    if _build(context, arch, build_name):
        print("Build Successful")
    else:
        print("Build Failure")
    generate_quality_settings(context)
```

to 

```
@task
def local_build(context, prefix='local', arch='OSXIntel64'):
    build_name = "thor-%s-%s" % (prefix, arch)
    fetch_source_textures(context)
    if _build('unity', arch, "builds", build_name):
        print("Build Successful")
    else:
        print("Build Failure")
    generate_quality_settings(context)
```

You should now be able to build a Linux version of THOR by running `invoke local-build --arch Linux64`. Note: to build a linux version of THOR you will need to have installed the linux build tools for Unity, if you haven't done this already you'll have to download the unity installer (which is not the same as just the unity editor, you can get this installer here https://unity3d.com/get-unity/download?thank-you=update&download_nid=49747&os=Mac) and be sure to hit the checkmark next to the linux build tools option during installation.

**Comment by hcv1027** [comment]
Hi @Lucaweihs , I just follow your patch.txt to modify my code and build it. But it dose not work. I let the agent move ahead continuously. And I print the value of `event.metadata['collided']`. It always show `False`, even when the agent collides the wall or something.

**Comment by hcv1027** [comment]
The collision handler `OnControllerColliderHit` in ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs is called all the time even when the agent does not move. And the `hit.gameObject.name` is always "Floor". So the `OnControllerColliderHit` will just return directly because below logic:
```c#
if (hit.gameObject.name.Equals("Floor"))
{
	return;
}
```
Is it normal? If I want to know whether my agent collides something like wall, desk or chair after it moves ahead/back/right/left. How can I do?

**Comment by winthos** [comment]
The `OnControllerColliderHit` is not used anymore for reporting or restricting movement. In previous versions of THOR the agent would move, and then if it hit something then`event.metadata['collided']` flag would be set and then the action would "fail" causing the agent to move back into its original position.

We found many inconsistent cases of movement using that logic, so now we have new movement logic in all our move actions. Currently, before the agent actually moves, a capsule cast of the agent's collider is sent through the scene to the desired location, and if that cast does not hit anything then the agent moves. Because we now check if we can successfully move before moving rather than resetting a failed movement after moving, you are seeing the results that you have found.

**Comment by Lucaweihs** [comment]
Hi @hcv1027, to be clear, can you give some details exactly how you're trying to get this collision info (i.e. a runable python script)? What @winthos said is correct but, if you are running things in python, you should be able to check what you collided with by looking at the `errorMessage` field from the metadata.

With respect to the code you pointed out, I don't think that
```
if (hit.gameObject.name.Equals("Floor"))
{
	return;
}
```
is the problem as `OnControllerColliderHit` will run with _every_ collider that the character controller runs into only one of which will be the floor. I think the problem has something to do with `collisionsInAction` never being emptied which means that, after colliding with an object once, the code
```
			if (!collisionsInAction.Contains(hit.gameObject.name))
			{
                                (...)
				Debug.Log("Agent Collided with " + hit.gameObject.name);
				collisionsInAction.Add(hit.gameObject.name);
			}
```
will not be run again. I believe should only be relevant if you're using the debugging mode in the unity editor though...

**Comment by hcv1027** [comment]
Hi @winthos , so how can I know if my moving action will cause collision? My requirement is that I want to train an navigation agent which can avoid obstacle, so I need collision information as feedback to compute reward.

Hi @Lucaweihs , I add log `Debug.Log("name: " + hit.gameObject.name);` at the beginning line in `OnControllerColliderHit` and then check the output log file. It will be output to "/MyHomeDir/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log". It always show "name: Floor". This function will return as the name is "Floor", without going to the block you mention.

**Comment by winthos** [comment]
If you attempt a `Move` action and it returns lastActionSuccess as false, then the move action failed because the agent would have collided with something.

**Comment by hcv1027** [comment]
Hi @winthos , it works, thank you.
