### ISSUE TITLE
How to know the scene size

### ISSUE THREAD

**Issue by edugm94** [allenai/ai2thor#118]
Hi to all,

I wonder if it is possible to know the maximum limits of a scene in order to create a discrete grid of possible positions within it. I know there is a method called: search_all_closed, but I want to know also the positions where an agent cannot be placed (because there is an object for example), so that I know possible positions of collision.
Can someone help me? 

Thanks in advance :)

**Comment by winthos** [comment]
```
controller = ai2thor.controller.BFSController()
controller.start()
controller.search_all_closed('FloorPlan28') # replace with whatever scene you want
print(controller.grid_points)
```
If you use the `search_all_closed` method, the resulting `controller.grid_points` will only have points that the agent can reach. This intrinsically includes information about where the agent cannot be placed.

**Comment by mattdeitke** [comment]
@winthos this seems to be an old issue. When would one still use the BFS Controller? Can all of this functionality currently be done using `GetReachablePositions``?

**Comment by winthos** [comment]
Yes, this functionality should be done using `GetReachablePositions` in the current build. The key is if any objects move or open/close, you will need to run `GetReachablePositions` again to grab the state of the scene after the change, since positions that were once reachable might not be (ie: opened a cabinet and now the area in front of that cabinet is not reachable)

**Comment by ekolve** [comment]
Closing - issue appears to be resolved (`GetReachablePositions` will return a grid of positions).  For anyone else that find this, [Scene Bounds](https://ai2thor.allenai.org/ithor/documentation/environment-state/#metadata-scenebounds) are also available now within the metadata.
