### ISSUE TITLE
Applying a learning agent

### ISSUE THREAD

**Issue by RossMelbourne** [allenai/ai2thor#12]
Hello,
Thank you for sharing this excellent simulation tool.  I have used Unity before so it feels familiar.  I noticed that in the machine learning code referenced here: https://github.com/caomw/icra2017-visual-navigation they used hdf5 dumps of the simulated scenes in Thor.  In the hdf5 file they can detect when collisions occur.  I did not see a method for detecting collisions in the controller code for Thor.  Am I missing something?
Thanks again for a very interesting simulation environment.  Are you planning on releasing a sample learning agent with the environment?

**Comment by ekolve** [comment]
Hi Ross,

One of the changes that has occurred since that paper was released was the ability to randomize the arrangement of objects and the state of openable items (cabinets, fridges, etc.).  When training this way there is an explosion of combinations that makes it infeasible to dump frames.  

We still have the ability to detect collisions within our Unity code, we just aren't sending it down in the metadata.  When a collision occurs during navigation, we will reset the agent to the spot it previously was and report a failed action back to the Python client.  If collisions are still of interest to you, please open a separate issue for that.

We are planning on adding an example to the project showing how to train an agent to perform semantic navigation (follow #13 to be notified when this is added).
