### ISSUE TITLE
Some confusions about the objects

### ISSUE THREAD

**Issue by Zzmonica** [allenai/ai2thor#121]
Hello,when I read the tutorial, here are some objects I can not figure out what are they suppose to be. And as follows:
1.`BowlDirty, BowlFilled`,`Dirt `which is actionable and has state? 
2.`EggFried,EggShell,LettuceSliced,MugFilled,PotatoSliced,SoapBottleFilled,TissueBoxEmpty,TomatoSliced,ContainerFull`,what's the actionable action suppose to be?

Sorry about the elementary questions put up here, but looking forward to your  answer.Thanks a lot~

**Comment by winthos** [comment]
Hi!

For you 1st question, the Bowl object itself is actionable, and the states that can be switched to from an action are BowlFilled and BowlDirty.

For your 2nd question, the sim objects you listed have actionable state functionality, but don't have a corresponding action that the agent can use to change their state by default. You will need to implement the agent's action yourself for whatever it is you want to do to the object. For example, you will probably want an explicit action for Filling a Bowl and a different explicit action for Slicing a Potato. 

Please note that all the object types you listed should be able to have their state changed as shown in the below link, where you must create a custom function that accesses the Animator component, gets the AnimState1 parameter, and changes that integer to change to different states. 

Please refer to this thread for more details about implementing your own actions: https://github.com/allenai/ai2thor/issues/31

Additionally, the only sim object you listed that you will need to make different logic for is the Dirt object, as that doesn't use the Animator parameter to change its state. You will need to make custom logic that does something like disables the game object components that have the dirt meshes on it. Please refer to [this Unity Tutorial for an example of how to disable objects.](https://unity3d.com/learn/tutorials/topics/scripting/activating-gameobjects)

**Comment by Zzmonica** [comment]
Thanks for your reply! Here are also some other questions:
Should I use the Dirt object to change the Bowl object's state into the BowlDirty? But how can  I change the BowlDirty object into the Bowl object ? And for slicing the potato I need use the knife? This kind of actions have you defined or I need to create by myself?
Looking forward to your reply!

**Comment by winthos** [comment]
The dirt object itself is just a decal that is on the floor or on the walls/mirror of certain scenes. The dirt itself is not used to change the Bowl to BowlDirty. 

To change the Bowl to DirtyBowl, or to change a DirtyBowl to a Bowl, you will need to make your own action similar to the Slice() function linked in my previous comment. You can add some additional checks to the Slice() function so that it will only succeed if the Agent has a Knife in its inventory, but by default there are no context sensitive restrictions to custom actions. You will need to create all these custom actions and any restrictions for using them yourself.

**Comment by Zzmonica** [comment]
When the bread object's state turn to sliced, the objectype change into breadsliced,right?
And about the `Mug` object, how can I make it into the full state ?

**Comment by winthos** [comment]
1. As long as you change the bread object's `AnimState1` value to 2, the SimObj script will update the object type for you. Your `slice` action only needs to change the `AnimState1`.

2. Changing the mug to the `full` state works the same way as slicing bread. Any objects that are actionable have multiple animation states, and swapping to them by changing the` AnimState1` int parameter will just change the model to that version. If you want to do something like make sure you bring the mug to a sink with water coming out, you will need to make new logic to reinforce that restriction yourself.

For example, if you just make a `fill` action that requires a target mug, it will instantly turn the mug into the filled version as soon as you switch it's `AnimState1` value to 2. If you want to additionally make sure the sink is on and water is coming out, you will need to access the sink's `AnimState1` and change it so that it is in the "on" state. Then, you could make some logic that if the sink is in the "on" state and you have a mug, you can then change the mug to filled.

3. The TissueBox, like all the other actionable objects, controls its state by changing the `AnimState` parameter on its Animator component.

4. Plates do not have the receptacle functionality, so by default they cannot have other objects placed on/in them.

Any object that is Actionable has an Animator component on them. 

You can open up the Animator window in the Unity editor by going to Window->Animator (make sure NOT to pick Window->Animation, that is different and not what you need)

Each Animator looks like this in the Unity Editor, and when you select an object in the Hierarchy view, it's corresponding Animator will be shown. 

![screen shot 2019-03-06 at 10 31 45 am](https://user-images.githubusercontent.com/17502636/53904686-83145600-3ffb-11e9-9ed7-5876a1f1d13e.png)

Click on the `Parameters` tab in the animator window to see all the object's states. Most objects have 4 states, but really only make use of 2 of them. Note that there is a single Parameter `AnimState1` which is just an int. Setting the `AnimState1` parameter to 0, 1, 2 etc. will change the state to whatever object version is linked to that animation state, and when doing so the SimObj Type will update accordingly. Note that some objects only have 2 states, others have multiple. 

You may find it useful to go into the Unity Editor and play around with the AnimState1 values to see what kinds of states each object has. If you have the Scene view open as well as the Animator window open in the editor, hitting Play will allow you to edit the AnimState1 value at runtime without having to do any scripting first. This is useful just to make sure you are setting an object to the state you want it to be in. 

![screen shot 2019-03-06 at 10 38 41 am](https://user-images.githubusercontent.com/17502636/53905137-9d9aff00-3ffc-11e9-940e-9f9dfdfa3892.png)

In the above example you can see that the editor is in Play mode, and I've selected a mug. Just type into the `AnimState1` field and you can change the state of the mug as shown in this second image. 

![screen shot 2019-03-06 at 10 39 08 am](https://user-images.githubusercontent.com/17502636/53905173-b1defc00-3ffc-11e9-905e-4d79a4d22b96.png)

Remember, you can do this programmatically using the example script linked in the other response. I will repost it here for convenience:

```
public void SliceObject(ServerAction action)
		{
			if(action.objectId == null)
			{
				Debug.Log("no target ID given");
				actionFinished(false);
				return;
			}

			foreach (SimObj so in VisibleSimObjs(action))
			{
				if(so.UniqueID == action.objectId)
				{
					so.Animator.SetInteger("AnimState1", 2);
					actionFinished(true);
					return;
				}
			}
		}
```

the `SetInteger()` function here lets you set `AnimState1` to whatever state you might need for the object. Remember that these are object specific, so to be sure you are state changing to what you want, go into the editor and double check the states at runtime.

**Comment by Zzmonica** [comment]
Got it! Thank you very very much !

**Comment by mattdeitke** [comment]
Closing as this appears solved. Feel free to re-open if there are any related follow-ups :)
