### ISSUE TITLE
an envirionment bug

### ISSUE THREAD

**Issue by YunlianMoon** [allenai/ai2thor#154]
There maybe an bug in AI2-THOR, when I use controller.step(dict(action='TeleportFull', x=, y=, z=, rotation=, horizon=)) function.
1. I found horizon (-60, -30) are look up degrees, while (30, 60) are look down degrees.
2. controller.step(dict(action='TeleportFull', x=, y=, z=, rotation=, horizon=60.0)) also works, while official website (http://ai2thor.allenai.org/documentation/actions) said that horizon valid values are -60 to +30 degrees.

**Comment by winthos** [comment]
Hello! 
So the `TeleportFull` action is a little strange, because it allows you to hard set the horizon value of the agent without any restriction. Normally, the `LookUp` and `LookDown` actions limit the agent's horizons in 30 degree increments. `TeleportFull` allows you to set whatever horizon angle you want, even something like 14.8 as there is no restriction of 30 degree increments.

The difference in the negative (-30, -60) "upward" look angles is due to the way horizon angles are defined within the Unity Framework.

![THOR_Horizon_Diagram](https://user-images.githubusercontent.com/17502636/55345247-47d33e80-5464-11e9-9a01-bb8c89c0cbd2.png)

I threw together this diagram to better describe why those numbers seem wrong. Because the X-axis is defined to be "right" facing given that the forward axis is defined by the Z-axis, the negative values indicate a rotation about the X-axis that ends up making the Z-axis point "upward." This is why the -30 horizon value angles the Agent's forward angle 30 degrees "up," while a 30 horizon angle will change the forward angle to 30 degrees "down."

We will update the documentation to more accurately describe how `TeleportFull` is used, as the way angles are set with `TeleportFull` are slightly different than `LookUp` and `LookDown`.
