### ISSUE TITLE
Rotation problem in TeleportFull

### ISSUE THREAD

**Issue by HuynhLam** [allenai/ai2thor#158]
The rotation values before and after TeleportFull were not consistent. E.g.
```
controller.step(dict(action='TeleportFull', x=point['x'], y=point['y'], z=point['z'], rotation=5, horizon=-30))
event.metadata['agent']['cameraHorizon'] = -30.0
event.metadata['agent']['rotation'] = {'x': 0.0, 'z': 0.0, 'y': 5.000000476837158}
```
or
```
controller.step(dict(action='TeleportFull', x=point['x'], y=point['y'], z=point['z'], rotation=5, horizon=10.0))
event.metadata['agent']['cameraHorizon'] = 9.999999046325684
event.metadata['agent']['rotation'] = {'x': 0.0, 'z': 0.0, 'y': 5.000000476837158}
```
or
```
controller.step(dict(action='TeleportFull', x=point['x'], y=point['y'], z=point['z'], rotation=10.0, horizon=40))
event.metadata['agent']['cameraHorizon'] = 40.000003814697266
event.metadata['agent']['rotation'] = {'x': 0.0, 'z': 0.0, 'y': 9.999999046325684}
```
I am not sure, is this a bug?
If yes, how to fix this? 
If not, how many degrees that the agent was actually rotated in these examples? 
Thanks in advance.

**Comment by winthos** [comment]
This is not a bug, it is due to the way the Unity engine stores those rotation values. Unity exposes the (x, y, z) Euler angles to define the rotation, but internally all rotations are stored as float-based quaternions. Because of this, the 3-axis values shown can sometimes look off or be rounded in weird ways because those returned rotation x, y, z, values are actually being retrieved from the internal quaternion notation and translated back to Euler values. 

This is a two-way operation, so setting the rotation via the TeleportFull action to "10" will orient the Agent correctly to the "rotation = 10" quaternion, but when the value is retrieved back from being a quaternion it might show up as rounded to 9.99 as you saw. Because the values were set by the TeleportFull action first, then translated to quaternion, then translated back it is actually still correct but due to floating point error in the "quaternion to euler" conversion, the returned value won't exactly match.

**Comment by HuynhLam** [comment]
Ok, thank for the answer.
