### ISSUE TITLE
Cannot drop or throw objects

### ISSUE THREAD

**Issue by hieudd98** [allenai/ai2thor#184]
Hi,
I'd picked object up by dict(action='PickupObject', objectId='_id_'). #bread in 'FloorPlan29'
However, I cannot drop or throw it by dict(action='DrophandObject') or  dict(action='ThrowObject', moveMagnitude=150.0).
Please help me to solve this problem.
Thanks.

**Comment by winthos** [comment]
It is most likely there is collision with another object preventing the action from completing. The bread is probably clipped inside the agent’s body collision. As noted in the documentation here (https://ai2thor.allenai.org/documentation/actions) we don’t allow the object to be dropped or thrown if it is actively colliding with other objects or the agent to prevent the physics system from shunting the dropped/thrown object in unpredictable ways. In Unity, when two objects are clipped into each other, physics resolves the clipping collision by forcefully shoving the objects out of each other’s collision. This is highly non-deterministic and can lead to bad edge cases like the bread being forced outside of the scene bounds because it was inside a wall when dropped.

To resolve this, you must reposition the object by some combination of moving the agent’s hand forward, or changing the look angle of the agent so that the held object is no longer colliding, then the drop/throw action will be allowed.

**Comment by ekolve** [comment]
Closing issue as it appears to be resolved.
