### ISSUE TITLE
open/close action

### ISSUE THREAD

**Issue by YunlianMoon** [allenai/ai2thor#194]
I found that, in some location, it is able to open receptacle but not allow to close it.

**Comment by winthos** [comment]
Could you provide some more details so we can investigate? The id of the receptacles as well as the location of the agent when interacting and scene name would be helpful.

**Comment by YunlianMoon** [comment]
for example, scene: FloorPlan1, position: {'x': -1.0, 'y': 0.9009992, 'z': 1.0}, rotation: rotation: {'x': 0.0, 'y': 270.0, 'z': 0.0} , view degree: 30, receptacle: Drawer|-01.56|+00.84|+00.20. Many situations like this in other locations and scenes.
My writing code return me an error so I found this.

**Comment by YunlianMoon** [comment]
test code:

import ai2thor.controller

env = ai2thor.controller.Controller()
env.start(player_screen_width=400, player_screen_height=300)
env.reset('FloorPlan1')
env.step(dict(action='Initialize', gridSize=0.5))

env.step(dict(action='TeleportFull', x=-1.0, y=0.9009992, z=1.0, rotation=270, horizon=30))
event = env.step(dict(action='OpenObject', objectId='Drawer|-01.56|+00.84|+00.20'))
print(event.metadata['lastActionSuccess'])
event = env.step(dict(action='CloseObject', objectId='Drawer|-01.56|+00.84|+00.20'))
print(event.metadata['lastActionSuccess'])

**Comment by winthos** [comment]
So any interactable sim object in THOR has a set of "visibility points" that are checked to determine if the agent can see the object. In this particular case, opening the drawer moves all of the drawer's visibility points, which are concentrated near the front of the drawer, outside of the camera's view, so trying to close the object fails because the drawer is no longer in "view" with respect to the Agent. Even though the interior part of the drawer is in the camera's viewport, the visibility points are not so to the Agent the drawer object cannot be found.

I will distribute the visibility points more evenly through the back of drawers so that they can remain visible even when viewed at extreme angles. These changes will be live in the next update. 

In the meantime, the best thing to do in cases like this is to move the Agent or rotate the agent's view so that the front part of the drawer (where the handles/knobs are) is in view of the camera. It will then be interactable and close correctly since it is in view.

**Comment by winthos** [comment]
@YunlianMoon Even though this issue is closed, just wanted to give an update that the fixes to drawer visibility are now live in Version 2.0
