### ISSUE TITLE
how to initialize pickupable objects into receptacles

### ISSUE THREAD

**Issue by YunlianMoon** [allenai/ai2thor#195]
I find that there are no objects contained in receptacles when receptacles are opened in almost all living rooms. I have tried the method controller.step(dict(action = 'InitialRandomSpawn', randomSeed = 0, forceVisible = false, maxNumRepeats = 5)), but it's useless.
How can I initialize objects into receptacles when I start ai2thor ?

**Comment by winthos** [comment]
Could you provide a few more details on your issue? Is it all receptacles not behaving correctly or is it just openable receptacles? Or is it you want to be able to spawn objects in pickupable receptacles (ie: spawn an apple on a plate)?

From your phrasing, it sounds like no objects are being randomly moved around at all, which should not be the case. Are you having issues specifically trying to spawn object in openable receptacles or is this just any receptacle? Receptacles cover a wide variety of objects from surfaces (table, sofa, sink, etc) to openable receptacles (fridge, cabinet, drawer etc.) and these are handled slightly differently. The forceVisible flag in the InitialRandomSpawn action restricts objects from being spawned inside openable receptacles. If the flag is set to false, then objects will have a chance to spawn inside closed receptacles based on the random seed. 

One thing to note is Living rooms do not have as many openable receptacles as Kitchens, so there will be a lower chance of objects in living rooms spawning in cabinets and drawers simply because there aren't a lot of them. Many of the drawers and cabinets inside living rooms are also smaller than kitchens, so only very small objects will be able to fit (keys, credit card, cell phone, and sometimes Newspaper if the drawer or cabinet is big enough).

**Comment by YunlianMoon** [comment]
@winthos 
I want to put some pickupable objects into openable receptacles when starting ai2thor, because there are no objects in openable receptacles (fridge, cabinet, drawer etc.) in living rooms. 

Are there some ways to achieve like this, in addition to use  controller.step(dict(action = 'InitialRandomSpawn', randomSeed = 0, forceVisible = false, maxNumRepeats = 5)).

**Comment by winthos** [comment]
I can confirm that `InitialRandomSpawn` does allow objects to be placed inside openable receptacles, but it seems that the rate at which they are being placed is not high enough for what you are trying to do. There is currently no support in the `InitialRandomSpawn` function to force the weight of objects spawning specifically inside openable receptacles. There are two solutions that I can think of that should be able to get you close to what you are trying to do given the current actions implemented:

1) If you are familiar with Unity, you can go into the living rooms and manually default the starting positions of objects inside drawers or cabinets by moving objects into Cabinets/Drawers etc. scene by scene. This is not a scaleable option, but if you take the time to edit the scenes yourself you will be able to fit as many objects as you want into drawers and cabinets. The danger of this is that it will take a long time, and you must be careful to make sure objects that are too big to fit inside the smaller drawers don't clip into the geometry. I do not recommend this option unless you only need objects inside openable receptacles for a few scenes, in which case I can help you curate them by hand.

2) You can attempt to try multiple `randomSeed` values and then filter out the bad seeds by reading the item metadata of the scene after using initialRandomSpawn. Because the object placement is based on the seed passed in, certain seeds might have many objects inside drawers/cabinets, while other seeds might have none. I would suggest trying a ton of different seeds and only using the ones that return object metadata of enough openable receptacles containing other objects. You can refer to the [documentation here](https://ai2thor.allenai.org/documentation/event-metadata) and check the object attributes for `receptacleObjectIds`.
