### ISSUE TITLE
Put object at specified point

### ISSUE THREAD

**Issue by rkruegs123** [allenai/ai2thor#243]
I am trying to pickup an object and then put it back **exactly** where I picked it up from. When i put it on the receptacle I picked it up from, it is often put in a different place. Is there a way to achieve this (e.g., specify the point you want to put an object on)?

**Comment by winthos** [comment]
There is not currently a way to pass in a specific point for objects to be placed. Most objects are defaulted to positions that are not exactly on the "grid" that is used to determine placement in receptacles. You might often find cases where you initialize a scene, pick up something, put it down, and it will be put down in a different position. If, however, you pick it up a second time after putting it down for the first time, it should be put into the same position if the agent hasn't moved.

The receptacle placement positions are dynamically calculated whenever the PutObject action is called, so note that for different SimObjects, even within the same Type category, the actual position the object is put can change since each Sim Object has collision unique to it. Additionally, not all receptacles of the same category are guaranteed to behave the same as they are unique sizes, orientations, and locations across scenes.

**Comment by rkruegs123** [comment]
Thank you for your response.

Allow me to clarify what you may be suggesting:

-If I pick up object A and put it back down, it may not be in the same place. However, if i pick Object A up again and put it back down, it will return to the starting position.

If this is true, why is this? If this is not true, could you clarify?

**Comment by winthos** [comment]
Option 2 is correct. The PutObject logic is not used to determine the starting positions (Position 1) of objects in a newly initialized scene.

**Comment by rkruegs123** [comment]
Thank you!
