### ISSUE TITLE
Draw 2D map

### ISSUE THREAD

**Issue by xli4217** [allenai/ai2thor#26]
Hi, I was wondering if there's a way to plot a 2D map with the agent navigating in it? Thanks

**Comment by ekolve** [comment]
Are you interested in seeing the agent superimposed over a 2D representation of the scene or do you just want to plot the agent's position in 2D?

If it is the latter, there is code in controller.py in visualize_points() that you should be able to use as a basis for plotting the agent's position using the metadata supplied from the event.

**Comment by xli4217** [comment]
Thanks for the reply. Having the agent superimposed over the scene representation would be ideal. Is it currently not support?

**Comment by ekolve** [comment]
That isn't supported and isn't trivial to do as it requires a second camera positioned in each scene in a particular way to capture the entirety of the scene.  The other issue we have is that the ceiling and lighting often get in the way of an overhead camera.  Third, the agent doesn't have a 'body' to visualize, so that is something else that would have to be added.

**Comment by xli4217** [comment]
I see, in that case I'll see what I can do with visualize_points().
