### ISSUE TITLE
Object Dimensions

### ISSUE THREAD

**Issue by shivanshpatel35** [allenai/ai2thor#307]
How can I get dimensions of the objects? 
I was expecting to find that in event.metadata['objects'][i](for i th object) but it does not have dimension information.

**Comment by winthos** [comment]
This metadata information was previously undocumented, but the [Object Attribute Section](https://ai2thor.allenai.org/documentation/event-metadata) of the documentation has now been updated to include `objectBounds`.

Note that this is not an exact measure of the dimensions of an object, but rather the object oriented bounding box that encapsulates the object. Also note that only objects that have the `Pickupable` attribute have bounds at the moment.

**Comment by shivanshpatel35** [comment]
Can we somehow access `objectBounds ` for the objects which have `Pickupable` attribute `False`?

**Comment by winthos** [comment]
Only `Pickupable = True` objects have object oriented bounds at the moment. We are looking into adding this information to the metadata of all objects in a future release.

**Comment by Tushar-N** [comment]
Is there a way to get `objectBounds` for `Pickupable = False` yet? I thought it would be enough to remove the check for 
```
if(simObj.PrimaryProperty == SimObjPrimaryProperty.CanPickup)
    objMeta.objectBounds = WorldCoordinatesOfBoundingBox(simObj);
```
in [L350](https://github.com/allenai/ai2thor/blob/2a3a57a08c3f6413e0b9b8dc28453c164853a279/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs#L350) of `PhysicsRemoteFPSAgentController.cs` and recompile, but looks like Unity does not return bounding boxes for these objects to begin with.

**Comment by winthos** [comment]
This feature is still in development and will be usable in a future release. Removing that line and recompiling won't do anything because the `WorldCoordinatesOfBoundingBox(simobj)` function call only works with objects with the tag CanPickup. Trying to use that call on any object will fail unless the object is `Pickupable = True`

**Comment by winthos** [comment]
As an update to this issue, the latest release version 2.4.0 now includes a world axis aligned volume that encapsulates all objects, these can be used for extremely rough estimations or volume. Note that because the axisAlignedBoundingBox is aligned to the world axis, if the object rotates then this axis aligned box will change volume. Pickupable objects also still have an object aligned bounding box, which are constant volume regardless of the object rotation.
