### ISSUE TITLE
Is there a way to access actions besides open, close, pick up, put down on actionable objects?

### ISSUE THREAD

**Issue by adaruna3** [allenai/ai2thor#31]
Hi Eric,

I was able to quickly get AI2Thor up and running and write some code that lets me explore the worlds via keyboard presses. Thank you for the simple tutorials and easy install! 

I have not been able to figure out how to use the diverse set of actions listed here: [object with new actions](http://ai2thor.allenai.org/tutorials/object-types). Do I need clone a specific branch of the repo or is this a complex change I would need to make using Unity? If so, how involved is it? I'm a robotics researcher and having the diverse set of actions would really help in my experiments.

Thanks,
Angel

**Comment by adaruna3** [comment]
Hi again,

Any suggestion on this? It will be tremendously helpful to know whether I am overlooking something or need to dig deeper and start using the project in Unity.

Angel

**Comment by roozbehm** [comment]
Hi,

Most objects have two states. You can implement the state change similar to open/close. For objects that have more than two states (e.g., microwave can be on/off/open/close) you should implement the logic. On the GitHub page we explain where the actions are implemented.

**Comment by adaruna3** [comment]
Got it, got it. Thanks for the reply!

**Comment by wcarvalho** [comment]
Hello, can you give a concise example of how to implement a new action? E.g., how would I implement slice and make sure that only certain objects would be sliced if given the objectID? 

I saw, "Actions are defined in unity/Assets/Scripts/DiscreteRemoteFPSAgentController.cs. Please refer to this page to check which objects are actionable." However, it is not clear how I would go about implementing an action.

**Comment by winthos** [comment]
@wcarvalho 

Hi! So a good example is if you look at the OpenObject() function in the DiscreteRemoteFPSAgentController.cs script. The python syntax to use this action is:

event = controller.step(dict(action='OpenObject', objectId="Fridge|0.25|0.75|0.05"))

The action name here is the exact name as the function in the DiscreteRemoteFPSAgentController script. The parameter passed in is the objectId, which is a unique string used to reference any Sim Objects you might find in a given scene.

To make any custom actions, you would want to follow that same format, which is basically pass in a ServerAction with any relevant values initialized to whatever you might need. For any targeted actions (do X on Y) you will need to pass in an ObjectId.

Here is an example of a Slice() action that can be used to slice Tomatos or Bread:

```		
public void SliceObject(ServerAction action)
		{
			if(action.objectId == null)
			{
				Debug.Log("no target ID given");
				actionFinished(false);
				return;
			}

			foreach (SimObj so in VisibleSimObjs(action))
			{
				if(so.UniqueID == action.objectId)
				{
					so.Animator.SetInteger("AnimState1", 2);
					actionFinished(true);
					return;
				}
			}
		}
```
There are a few things to note here: First you need to make sure if the action fails, a call of actionFinished(false) must be sent so that Metadata can be updated correctly. Similarly, if the action succeeds, a call of actionFinished(true) must be sent.

Finally, this slice function will only work for Tomatos, Potatos, Bread, and other Sim Objects that already have a sliced version of the model linked to the prefab in Unity. This will not work for trying to slice incompatible objects, like Slice() -> Chair, as the 3d model asset for a sliced chair literally doesn't exist. If you would like to make any specific custom actions that don't exist in the framework at all, you will need to dig through some Unity documentation and get familiar with the C# side of the framework. This Slice() action just happened to be set up, but in this case there was no Action that directly changed the values that would cause it to turn into a sliced version.
