### ISSUE TITLE
The controller function doesn't accept scene and gridSize arguments as described in the documentation!

### ISSUE THREAD

**Issue by Alrick11** [allenai/ai2thor#326]
I have been getting this issue for some time now. It would be great if you could help me out with this. Thanks in advance!!

Code snippet:

`In [27]: import ai2thor

In [28]: import ai2thor.controller

In [29]: controller=ai2thor.controller.Controller(scene='FloorPlan30', gridSize=0.25)
Traceback (most recent call last):

  File "<ipython-input-29-89a03b88414d>", line 1, in <module>
    controller=ai2thor.controller.Controller(scene='FloorPlan30', gridSize=0.25)

TypeError: __init__() got an unexpected keyword argument 'scene'`

**Comment by mattdeitke** [comment]
Hi!

Really sorry about this! The documentation expresses the newest version of using **THOR from the GitHub repository**, but the **pip install command needs to be updated** to catch up to the changes in GitHub repository (which will likely happen in the next day or so).

In the meantime, there are 2 options:
1. **Locally clone the GitHub repository**, then import that cloned directory, e.g.,
```
import os
os.chdir('<ai2thor-repository>')
import ai2thor

controller = ai2thor.controller.Controller(scene='FloorPlan30', gridSize=0.25)
```

This allows you to use the newest, documented, syntax.
_Note: you might need to uninstall the pip version of AI2-THOR to avoid conflicting imports._

2. **Continue using the current pip install of AI2-THOR**, with the older syntax. It's pretty similar, but a tad more confusing with potentially unexpected bugs, basically:
```
import ai2thor

controller = ai2thor.controller.Controller()
controller.start(<optional height and width parameters>)
controller.reset(<sceneName>)
controller.step(action='Initialize', <optional other initialize parameters (e.g., gridSize)>
```
Also, if you ever call reset after initialize, you need to immediately call 
```
controller.step(action='Initialize', <optional other initialize parameters (e.g., gridSize)>)
```
otherwise there may be unexpected bugs. (This is fixed in the latest version that you were trying to use and `start`, `step(action='Initialize')` will pretty much be deprecated.)

I'll let you know as soon as the pip command is updated!

Matt.

**Comment by Alrick11** [comment]
Thank you Matt for the quick reply. Do let me know when you update the pip
command!

Thanks

**Comment by ekolve** [comment]
Version 2.2.0 has been pushed to pypi.  You can now use: pip install ai2thor and use the code you opened the issue with.

**Comment by Alrick11** [comment]
Thank you!!
