### ISSUE TITLE
Where can I see all actions I can execute 

### ISSUE THREAD

**Issue by GELIELEO** [allenai/ai2thor#337]
I want to know all the actions I can execute, because sometimes I want to know whether I can execute some action. Where can I see all the actions and their descriptions I can take

**Comment by mattdeitke** [comment]
Check out the [actions section on our documentation](http://ai2thor.allenai.org/documentation/actions/).

**Comment by GELIELEO** [comment]
@mattdeitke  Thank you for your reply. But some actions like 'ToggleMapView' actually can not be found in [actions section on our documentation](http://ai2thor.allenai.org/documentation/actions/).

**Comment by winthos** [comment]
Actions not listed in the documentation are either experimental or not fully supported in some way (either in development or potentially deprecated). The 'ToggleMapView' was made for an internal project, and was only guaranteed to function on a small subset of scenes. Since it is not guaranteed to be compatible with every scene, it is not officially documented (although it should be compatible with at least 90% of the scenes).

If you would like to look through all possible actions, you can refer to any functions that take a `ServerAction` parameter [in the PhysicsRemoteFPSAgentController script](https://github.com/allenai/ai2thor/blob/c73393b4bc6bfaf8997b6884fdcb65de38c6d871/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs#L1964l). The previous link is to an example of such a function, specifically the `MoveAhead` action.

**Comment by ekolve** [comment]
Closing as issue appears to be resolved.
