### ISSUE TITLE
Initialize a pickupable in agent's inventory

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#357]
Can I initialize a pickupable in agent's inventory and is it possible to have more than one pickupable in agent's inventory at the same time? At the same time, if there are multiple same objects (say 3 mugs), is there a way to remove all but left with single one?
Thanks for your reply.

**Comment by winthos** [comment]
It is not currently possible to initialize a scene with a specific pickupable object in the "inventory." You can also only pick up a single object at a time. You can use the `RemoveFromScene` action documented [here](https://ai2thor.allenai.org/ithor/documentation/actions/miscellaneous-actions/) to remove select objects from a scene by their objectId.

**Comment by zyzhang1130** [comment]
I see. But is it possible to initialize agent's location while keeping the environment as it is?

**Comment by winthos** [comment]
Yes, if you don't do any actions that edit the environment, like the `RemoveFromScene` action, you can use the Teleport actions to change the initial position of the agent's location after initializing a scene.

**Comment by zyzhang1130** [comment]
I am thinking of an alternative to achieve the same thing:  to save the environment setting (everything apart from the agent) and load it later. Is there any way to do so?

**Comment by winthos** [comment]
Please take a look at the [initialization actions](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/) in our documentation. I believe you will be able to achieve what you are trying to do with a combination of those actions. For example, if you want to use a random seed to shuffle a scene's objects around, you can reset and then initialize with the same seed in order to reproduce the environment setting.

If you want to, for example, reset a scene so that every time a `Bread` object is defaulted to the `BreadSliced` state, you can use the `RandomToggleSpecificState` action detailed in the initialization documentation to make sure each repeated episode defaults to the same state of all `Bread` in a scene being sliced by default.

**Comment by zyzhang1130** [comment]
It is not really generating the same scene by a random seed what I want. Rather, the scene I would like to save is a result of the activity of agent. For example, the agent put an apple inside a fridge and I would like to save this setting. The agent's activity is not predictable however.

**Comment by winthos** [comment]
If you again check the [initialization actions here](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#restore-object-positions) there is an action called `SetObjectPoses` that can be used to reset objects back to a position after a metadata dump, for example after an agent puts an apple in the fridge. The only things this won't work for is if the agent performs an action such as slicing/breaking an object, as those are one-way, destructive changes to an object within an episode. The `SetObjectPoses` initialization action will allow you to reset positional changes, however.
