### ISSUE TITLE
The range of pickup/put object

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#364]
Hi, may I ask is it as long as I specify the Id and the location of an pickupable object it can be pickup/put (provided no obstruction), regardless of how far the object/location to put is? In other words, what is the range of agent interacting with an object? Does it have anything to do with the sight range of the agent?

**Comment by zyzhang1130** [comment]
I just saw the 'concept' section in the documentation. Am I correct to say in order to shorten the distance in which the agent can pickup/put object, I just need to adjust the 1.5 meter threshold for agent? If yes which metadata it is I need to change?

**Comment by winthos** [comment]
An object is only interactable if it within sight range of the agent. If you have an objectId and the object is within the [`visibilityDistance` of the Agent ](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/) (defualt value 1.5 meters) and the object is unobstructed, you can interact with it using Pickup/Put. 

Changing the `visibilityDistance` parameter on agent initialization will be what you nee dto do in order to shorten or lengthen the range of interaction of the agent.

**Comment by zyzhang1130** [comment]
Noted. Thank you for your reply.
