### ISSUE TITLE
Pull/push object 

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#365]
Hi, may I check with you how come in the documentation provided here https://ai2thor.allenai.org/ithor/documentation/actions/object-interaction/#pull-object for push/pull object, it says need to specify objectId, but the objectId is not in the sample code below?  
Also is there a corresponding property like 'pullable' or 'pushable'? According to the documentation some non-pickupable objects are also push/pull-able (like chairs,sofa) so how could I tell exactly which object to pull/push (previously I use the demo to identify which are the interactable objects but it seems things like chairs,sofas, trash bins, etc cannot be interacted with in demo because in demo only 'pickup' and 'put' are avilable) ? 

Thank you for replying.

**Comment by winthos** [comment]
The Push/Pull action examples were missing the objectId in the example script. Both actions require an objectId in order to push a specific object, and the documentation has been updated with the correction.

There is no pushable/pullable property as only `Pickupable` objects are able to be pushed/pulled at this time. We are working on a future release that will include larger furniture objects like chairs and sofas as push and pullable. This description has also been updated in the documentation.

**Comment by zyzhang1130** [comment]
noted. thanks for your reply.
