### ISSUE TITLE
Potential bug for box?

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#372]
Hi, I spotted this issue in scene FloorPlan304:
After I picked up the box in that scene, there is no way for me to get rid of that box. I tried put (obviously didn't work because the floor/ground is not defined as a valid Receptacle), throw (with magnitude 60, 150, 230) and drop with all possible horizon, for both with box open and closed and none of them can let the box out of agent's inventory. I suspect it is a potential bug?

**Comment by winthos** [comment]
This is not a bug. It is possible for certain objects to not have a valid free space in a target receptacle to be placed back in. All objects are placed in scenes manually in their default positions, and this manual placement in-editor does not use the logic used int he PutObject action. 

In this case, you can use the `RemoveFromScene` action detailed [in the documentation here](https://ai2thor.allenai.org/ithor/documentation/actions/miscellaneous-actions/) in order to remove the object from the scene.

You can also use the `DropHandObject` action to simply drop the box somewhere in the scene. This uses the physics engine to resolve where the box will fall, rather than the more restricted positional snapping used by the `PutObject` action. The details on how to use this action [can be found here.](https://ai2thor.allenai.org/ithor/documentation/actions/object-interaction/)

**Comment by zyzhang1130** [comment]
It worked in conjunction with MoveHandAhead. I didn't realize it is because the Box is too big. Thank you so much.
