### ISSUE TITLE
camera height

### ISSUE THREAD

**Issue by gophermmq** [allenai/ai2thor#394]
Hi,

I need to set the camera height in my projects. During the initialization, I set the parameter 'CameraY'. But I found the default camera height from the ground is around 1.47 meters. The camera height cannot be any lower even if I change CameraY value (e.g. to 0.5, 0.1). Could I ask how to change the agent's camera height? Thank you very much.

Best regards,
Minghan

**Comment by winthos** [comment]
Hello!
Our documentation had an error in the description of the CameraY initialization parameter. In the most recent version, the way our cameras are setup for each of the different controller types and agent modes has caused that value to not be accessible at this time. The default CameraY value (0.675) was misleading because it was not the height off of the floor that the camera sat at, but rather the distance in the camera's local space that it was offset from the center of the Agent. Because of this, the CameraY value was difficult to use in a meaningful way and access to it was deprecated in the latest release.  The documentation has been updated to reflect this.

In a future release, we will add in a more robust way to adjust camera height on initialization, but for now you do have an option to adjust camera height from the default with an action.

You can use the `Crouch` action to lower the camera height into the crouching position, but this will not allow you to adjust exactly where that position is.

**Comment by gophermmq** [comment]
Got it. Thanks.
