### ISSUE TITLE
Bug in object-selection

### ISSUE THREAD

**Issue by wcarvalho** [allenai/ai2thor#400]
During my experiments, I found that when the agent selected "Pickup Plate" on Floorplan24, both the pan on the stove and the plate were picked up. I.e., sometimes, when the agent selects an object to pickup, it will pickup **additional** objects. This is hard to reproduce because it was 300K steps into training. I'm using version 2.3.4.

Note, I am using `InitialRandomSpawn` to randomly spawn the objects where I pick a value between 1,10000 after every reset. 

![image](https://user-images.githubusercontent.com/6220222/83175132-6fb24680-a0e9-11ea-904c-fa29891f7b69.png)
![image](https://user-images.githubusercontent.com/6220222/83175343-be5fe080-a0e9-11ea-9339-59c9bd295c30.png)

**Comment by winthos** [comment]
This is an edge case due to the ability of the framework to allow objects placed on receptacle objects to be picked up if the receptacle is picked up. There is zone of space defined above each receptacle object that denotes whether the receptacle contains other objects. If another object's collision is anywhere within this zone, it will be considered "contained" by the receptacle and will be picked up with the receptacle if the receptacle itself is picked up.

This result appears to be due to the collision of the frying pan being just enough over the threshold of the plate object's receptacle zone that it is considered to be "contained" by the plate. 

So the agent is supposed to be able to pick up additional objects if they are contained, but due to the weird, long shape of the frying pan's collision it seems to be being detected as contained by the plate. I will investigate if there is a clean way to filter out edge cases like this, but due to the reliance on Unity's physics engine and trigger colliders to resolve this interaction, in the meantime it would be best to filter out and ignore cases like this if that is a possibility.
