### ISSUE TITLE
is it possible to move the large furniture?

### ISSUE THREAD

**Issue by gophermmq** [allenai/ai2thor#411]
Hi,

I was trying to get more environments by changing room layouts. Could I ask whether it is possible to move large furniture e.g. sofas, dining tables in AI2thor? Thank you very much.

Best regards,
Minghan

**Comment by winthos** [comment]
Hello!

Large furniture is not currently compatible with our object randomizer in the same way that our small, "pickupable" objects are. There are a few options that you could use to try and change room layouts even more by moving large furniture:

You could use the [Place Object At Point Action](https://ai2thor.allenai.org/ithor/documentation/actions/object-interaction/#place-object-at-point) to try and move furniture around. This action allows you to place objects with a coordinate above a valid receptacle, and then it will place it flush with the receptacle below that coordinate. 

Additionally, many of the actions on the [Object Interaction page](https://ai2thor.allenai.org/ithor/documentation/actions/object-interaction/) of our documentation can be used to push, pull, or otherwise manipulate furniture objects about a scene. You could do something like adding a furniture rearrangement step to the initialization of a scene. The agent could teleport to various locations and shove objects around before beginning the actual task in the scene.

**Comment by gophermmq** [comment]
Thank you very much for your suggestions. I will give them a try.

**Comment by XiaoLiSean** [comment]
@gophermmq @winthos  Hi, thanks for your clarification. I came cross a issue to place furniture at desired points #472. For movable but not pickupable objects such as sofa and toaster, the placeObjectAtPoint action won't work and the code just stuck at that line. I'm using iTHOR version 2.4.11.

**Comment by winthos** [comment]
The `PlaceObjectAtPoint` action is able to move "moveable" objects as well as pickupable. I believe the issue you might be having is that because "moveable" objects are generally much larger than pickupable, the coordinates you are using to try and move things like the sofa, toaster, or a chair to do not have enough free space to allow the placement to succeed. `PlaceObjectAtPoint` will only move the object if the zone around the given coordinate is free of obstruction, this is to prevent things like moving a sofa in a way that would cause it to clip through the wall and stick outside of the room.

**Comment by XiaoLiSean** [comment]
Thanks for your suggestion. I actually tried place both moveable and pickupable objects such as 'Bread|-00.52|+01.17|-00.03' in FloorPlan1. The example in #472 is trying to move the bread towards the middle of the CounterTop for 5cm. But the code just stuck at the line which is calling action 'PlaceObjectAtPoint'. If my observation is accurate, there is no obstruction to prevent this displacement. Hope you can help me out. Thanks!
