### ISSUE TITLE
Initialize an object based on its objectId

### ISSUE THREAD

**Issue by zyzhang1130** [allenai/ai2thor#431]
It was mentioned in the documentation as to how to initialize an object based on a set of given position coordinates. I think it should be also possible to spawn objects based on only objectId since it was mentioned in the documentation that objectId is composed of the object’s type and the position coordinates of the object in the scene, but I am not sure not to do it.

**Comment by winthos** [comment]
We currently do not have a way to spawn new objects into a scene based on their objectId. The objectId of an object is generated based on the object's object type and the location that they exist in within a specific scene. Currently, the various way to initialize a scene allow you to shuffle around the objects that already exist in any given scene, or to reset the objects in the scene to a previous position using the documented action you mentioned.

**Comment by zyzhang1130** [comment]
Does that mean the information regarding the object location cannot be extracted from objectid?

**Comment by winthos** [comment]
The position coordinates that are part of an object's objectId are generated when the scene is initialized, and are updated if the objects have been shuffled around via the `InitialRandomSpawn` action. Besides those actions, the objectId will not change in a given episode.

To obtain the object's current position coordinates after doing something like moving the object to a new location with `Pickup` or `Push`, check the object's position in the Object attributes of the event object returned after any action: (https://ai2thor.allenai.org/ithor/documentation/metadata/#object-attributes-)

To summarize, the object's position can change, and you can grab that information from the Object attributes metadata. You can then use that value to initialize a scene using the `SetObjectPoses` action (https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#restore-object-positions)

For example, you could do something like initialize a scene, have your agent pick up and move an apple, then grab that apple's position info from the metadata. Then, in a new episode, you can initialize the scene so that the apple is instead moved into the position from the previous episode using the `SetObjectPoses` action

**Comment by zyzhang1130** [comment]
From the first paragraph, it looks like I still can recover the object's initial position?  The objectIDs are from another experiment and what I would like to do is to simply recover the initial position of those objects in that experiment.

**Comment by winthos** [comment]
If the other experiment is using the same version of THOR, then it should be recoverable in that way. Note that between versions of THOR, it is not 100% guaranteed the object initial positions will be the same due to potential changes in the framework.

**Comment by zyzhang1130** [comment]
That's good to know because the ai2Thor version should be the same.  May I know how is the initial position encoded into the objectID?

**Comment by winthos** [comment]
When the scene first initializes, all objects have their current positions encoded into their objectID. This is the same position information as what is found in the object attributes metadata.

If you choose to use the `InitialRandomSpawn` action to shuffle objects around, the objectIDs are overwritten since their new initial position is effectively different.

**Comment by winthos** [comment]
Yes, that is correct

**Comment by zyzhang1130** [comment]
noted with thanks
