### ISSUE TITLE
How to slow down the presentation

### ISSUE THREAD

**Issue by faylsaac** [allenai/ai2thor#440]
The presentation is so fast that i can't see claerly.

**Comment by mattdeitke** [comment]
Hey @faylsaac

Which presentation are you referring to?

Matt.

**Comment by faylsaac** [comment]
Take the demo in https://ai2thor.allenai.org/ithor/documentation/overview/examples/ for example, I get an apple and then put it in the oven. This task  demos too fast, I didn't see what the agent have gotten clearly and the agent put it in the oven. So I want to slow down the agent's action

**Comment by mattdeitke** [comment]
It's meant to be as fast in order to run as many experiments as possible in the shortest amount of time. To slow things down for visualizations, one could use `time.sleep`:
```python
from ai2thor.controller import Controller
import time
c = Controller()
for _ in range(100):
    c.step('MoveAhead')
    time.sleep(2)
    c.step('MoveBack')
    time.sleep(2)
````
Here, sleep refers to the number of seconds to wait in between actions.

As an alternate approach, you could save images to a local directory and view them after the fact, as in:
```python
from ai2thor.controller import Controller
from PIL import Image
c = Controller()
for i in range(100):
    event = c.step('MoveAhead')
    Image.fromarray(event.frame).save(<INSERT PATH>)
    event = c.step('MoveBack')
    Image.fromarray(event.frame).save(<INSERT PATH>)
```

- Matt :)

**Comment by faylsaac** [comment]
3q very much  ^_^      ( 3q == thx )
