### ISSUE TITLE
Place Object At Point won't work in iTHOR

### ISSUE THREAD

**Issue by XiaoLiSean** [allenai/ai2thor#472]
I just update my AI2THOR version to 2.4.11  to solve the issue #452 using 
`conda install -c conda-forge ai2thor`
 The action type for getting spawn coordinate above receptacle works just fine.
`event = controller.step('GetSpawnCoordinatesAboveReceptacle', objectId='CounterTop|1|1|1', anywhere=True)`
However, the action for placing movable but not pickupable objects such as chair, toaster and sofa at a point won't work.
`event = controller.step(action = 'PlaceObjectAtPoint', objectId='Toaster|1|1|1', position=dict(x=-1.25, y=1.0, z=-1.0))`

**Comment by winthos** [comment]
Could you check if there is any error messages returned with the `actionReturn` metadata? The `GetSpawnCoordinatesAboveReceptacle` action does not check to see if those coordinates are valid for the object to spawn. It only gets potential coordinates to try as a reference. The actual `PlaceObjectAtPoint` action has a check to see if a given potential coordinate has enough free space to place the object, so it's possible that even though you are passing in a coordinate that particular coordinate is not valid.

**Comment by XiaoLiSean** [comment]
Thanks for your suggestion. I have a short testing code for moving bread to the mid of the couterTop in FloorPlan1:
`    controller = Controller(scene='FloorPlan1', gridSize=0.25)
    controller.step('ChangeResolution', x=SIM_WINDOW_WIDTH, y=SIM_WINDOW_HEIGHT)
    controller.step('Pass')
    event = controller.step(action='RotateLeft', degrees=90.0)
    breadId = 'Bread|-00.52|+01.17|-00.03'
    # counterTopId = 'CounterTop|-00.08|+01.15|00.00'
    objs = [obj for obj in event.metadata['objects'] if obj['objectId'] == breadId]
    spawn_pose = objs[0]['position']
    spawn_pose['x'] +=0.05
    time.sleep(5)
    print(spawn_pose)
    event = controller.step(action = 'PlaceObjectAtPoint', objectId=breadId, position=spawn_pose) # stuck
    time.sleep(5)`
The code just stuck at that line and I'm certain the spawn_pose is feasible.

**Comment by XiaoLiSean** [comment]
Hi, I just noticed that your AI2THOR version has been updated to Version 2.4.15 in Conda
[https://anaconda.org/conda-forge/ai2thor](url)
I just updated my AI2THOR version and the code using action of 'PlaceObjectAtPoint' did not stuck. But the object still won't move.

**Comment by winthos** [comment]
I believe the issue you are observing is that the bread itself is preventing it from moving only 5cm. When the `PlaceObjectAtPoint` action is called, nothing in the scene actually moves until the coordinate you pass in returns that the area around it is clear. If you are only moving the bread a small distance, the bread itself can cause this action to fail because the area isn't technically clear. So this behavior you are seeing is working as intended, and if you do want to move the bread only 5cm you may need to run the action twice, one to move the bread out of the area entirely, and then another to move it 5cm from its original position.
