### ISSUE TITLE
Place third party camera at ceiling corners

### ISSUE THREAD

**Issue by sushrut3** [allenai/ai2thor#509]
I want to place third party cameras at corners of the room (ceiling). For this I get coordinates of the ceiling. Ceiling is not an object in metadata so how do I these locations ?

**Comment by mattdeitke** [comment]
It's still not officially supported, see #445, but for the ceiling image, you can currently run:
```python
from ai2thor.controller import Controller


def get_ceiling_image(controller):
    # puts the camera in the ceiling, then puts it back with the robot
    event = controller.step('ToggleMapView')
    controller.step('ToggleMapView')
    return event.frame


controller = Controller()
for _ in range(5):
    rgb_robot_frame = controller.last_event.frame
    ceiling_frame = get_ceiling_image(controller)
    
    # perform an action
    controller.step('RotateRight')
```

**Comment by sushrut3** [comment]
Thanks for replying. This gives the view of the entire floor plan. 
But I wanted views/frames from multiple third party cameras placed at ceiling corners. Or maybe if I could just the coordinates of the ceiling so that I could place these cameras there.  

Is there anything else that I could try for my requirement.

**Comment by winthos** [comment]
So you are correct that the ceiling is not a sim object. Even if it were, the coordinates of its position would not be enough to place cameras in the corners since the ceiling object’s coordinates are not guaranteed to be consistently at a corner of the mesh, it is most likely going to be at the center of the mesh. Additionally there are often multiple unity game objects that make up the entirety of the ceiling, so exposing the “corners” of a ceiling is not very feasible at the moment.

If you want exact spatial coordinates for where to put third party cameras, you can open the scenes you are interested in Unity Engine and get the coordinates  by placing empty game objects in various places in the scene, and then taking their position information from their transform components. You can even add camera objects via the editor and preview how the point of view of that camera will look. Note that adding camera objects in the editor directly is not the same as the third party cameras that are added via the python controller, as third party cameras have more setup that is handled by the action that allows it to be used in THOR itself instead of just the unity engine.

**Comment by sushrut3** [comment]
Okay, thank you. I think I've enough as of now.
