### ISSUE TITLE
No valid positions to place object found

### ISSUE THREAD

**Issue by shuyanzhou** [allenai/ai2thor#525]
Hi, 

I found the agent sometimes cannot put an object with the error message "No valid positions to place object found". The rendered image looks reasonable to me. For example, the agent cannot put the book on the sofa with forceAction=True.

![image](https://user-images.githubusercontent.com/29911200/98431544-4af0d080-2084-11eb-868e-e99d79f5e4a1.png)

**Comment by mattdeitke** [comment]
Hey!

How are you targeting the receptacle with put? For instance, are you passing in
```python
# target via objectId
controller.step('PutObject', objectId="TableTop|0.25|-0.27|0.95")

# target via (x, y) based on RGB frame
controller.step('PutObject', x=0.2, y=0.5)
```
I suspect in your image, if you try targeting with, say `x=0.5, y=0`, it'd fail with your error message.

It's also worth mentioning that the agent can simply drop the object without specifying additional parameters:
```python
# setup
from ai2thor.controller import Controller
c = Controller()
# ... get into position
c.step('DropHandObject')  # optionally with forceAction=True
```
With dropping, it's often used in tandem with [Held Object Manipulation](https://ai2thor.allenai.org/ithor/documentation/actions/held-object-manipulation/), which could be used to stretch the arm out and place the book on the couch, for instance.

**Comment by shuyanzhou** [comment]
Hi @mattdeitke, thanks for the reply. I am using the `objectId` for the `PutObject` action. I tried to use `DropHandObject` but then I got this error: 
> Book_6ede4fbf can't be dropped. It must be clear of all other collision first, including the Agent.

It turns out that the two keychains on the left side of the sofa block the agent from putting the book. After I remove these two keychains, the agent could put the book on the sofa. Considering the size of the keychains, this does not make a lot of sense to me. Any ideas? Thanks!

**Comment by shuyanzhou** [comment]
A more general question, I am wondering if there is any way that the agent could put the in-hand object to the receptacle as long as the receptacle is visible?

**Comment by shuyanzhou** [comment]
Hi @mattdeitke, any update on the thread? Thanks

**Comment by winthos** [comment]
Hello! I'd like to explain a bit more about how the `PutObject` action actually works, which may explain the behavior you are seeing.

First, the `DropHandObject` is failing most likely because the book is inside the agent's collider. Notice the error message says "...It must be clear of all other collision first, including the Agent."

Here is a rough diagram of what is happening. The Cyan capsule represents the Agent's collision. The Triangle represents the agent's camera and camera frustrum, and the red object represents an object held by the agent. This is in a 2D side view.

![CantDrop](https://user-images.githubusercontent.com/17502636/98991689-1005f700-24e1-11eb-8c4d-faa2067f9bb8.PNG)

When the agent picks up an object, it's position is kept constant relative to the agent's camera. This means, when you change the agent's horizon when you `LookDown` the picked up object can often intersect with the agent's own collision. When you try and `DropHandObject` in this orientation, the action fails with the message you are seeing to prevent dropping an object inside the collider of the agent. If you pass in `forceAction  = True` to the drop action, it will allow the object to be dropped but the behavior of the object will be highly chaotic because the collider of the object will be shoved out of the agent's collider in a random way.

To fix this, there are a few options. You could angle the agent's camera using `LookUp` so that the held object is clear of the agent collider like so:

![rotateCamera](https://user-images.githubusercontent.com/17502636/98991910-58bdb000-24e1-11eb-821b-98260c6f2edd.jpg)

You can also use some combination of the MoveHand actions (https://ai2thor.allenai.org/ithor/documentation/actions/held-object-manipulation/#move-hand-forward) to move the object out of the agent's collider:

![moveObject](https://user-images.githubusercontent.com/17502636/98991987-73902480-24e1-11eb-819f-54d041011f99.jpg)

Second, I'd like to explain a bit more about how the `PutObject` action works and why I believe you are seeing it succeed when you remove the keychain.

Here is a top down diagram that shows some details about how the agent tries to place an object on some receptacle.

The blue circle is the agent. The black circle around it is the agent's max visibility distance. The Triangle is an object the agent is trying to place. The big grey box is some receptacle, while the little dots on the box are potential spawn points that the triangle object will be attempted to be placed at.

![MaxVis_PutObject](https://user-images.githubusercontent.com/17502636/98992294-e26d7d80-24e1-11eb-89a9-5e36dcbdc934.PNG)

Notice that while this receptacle is visible to the agent, The majority of the spawn points on the receptacle are outside of the Agent's view, due to them being outside the visibility distance. When `PutObject` is called, all spawn points that would cause the placed object to become `isVisible = False` are filtered out automatically in order to prevent a case where the agent puts an object on a receptacle, but suddenly that object's metadata becomes `isVisible = False.` This is intended behavior, as placing an object like in the image, where the red "X" is would be confusing behavior.

What I believe is happening is, based on your image, your agent is far away from the sofa, and the only free spawn points are the ones very close to the front edge of the sofa. When you remove the keys, it frees up just enough space so that the book can be placed on the front edge of the sofa. The spawn points near the back of the sofa are being filtered out and not checked at all, most likely because they are outside of visible range.

To check this, set up the exact parameters to reproduce the image you posted above, but before you try and `PutObject` try moving the agent forward more. Once you are closer to the couch, it should allow you to place the book on more of the couch's surface.

Note that `forceAction = True` in this case does not allow the placed object to be placed outside of the agent's visible distance. Currently, forceAction only allows the `PlacementRestrictions` defaults of an object to be ignored. The reason for this is the logic used to try and put an object at various spawn points on a receptacle have a lot of steps tied to the agent's camera position and frustrum. I will make a note that we should add the option for `forceAction` to ignore visibility constraints such as this, as this will require a rework of the entire logic.

**Comment by mattdeitke** [comment]
One other note worth mentioning that might be non-obvious: isVisible doesn’t actually mean isVisible in practice, but rather isVisible and is within the visibilityDistance set upon initialization (default 1.5 meters). (This decision was done for the context of object navigation, where one is only successful if they’re within 1.5 meters from that object and looking at it.)

If you want isVisible to return True if the agent is looking at an object, regardless of the distance from the agent to that object, initialize the visibility distance to some large number that’s bigger than the entire scene:
```python
from ai2thor.controller import Controller
c = Controller(scene='FloorPlan28', visibilityDistance=25)  # 25 meters
```

This should allow you not to need to move closer to the couch in order to call put.

**Comment by shuyanzhou** [comment]
@winthos @mattdeitke Thanks a bunch for the detailed explanations!
