### ISSUE TITLE
Feature request: PutObject with (x, y) should influence target location

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#540]
With the new PutObject interface that allows specifying a normalized (x, y) position on the screen where the receptacle object is, it would be awesome if that (x, y) position were further propagated to select a resting position for the pickupable object on the receptacle object. 

My understanding is that currently a series of candidate positions are constructed on the receptacle object where the pickupable object can fit, and that these are sorted randomly before one is selected as the target location for the pickupable object. Instead of a random sort, with the (x, y) specification, these could be ordered by proximity to the specified (x, y) so that the pickupable object goes close to the location specified by the API call.

This feature would reduce friction with the API call for PutObject, especially in cases where the receptacle object is large enough that placement happens at the corner of / off screen (e.g., L shaped counters, floors, large tables).

**Comment by winthos** [comment]
This is definitely some functionality that can be added in. I will make a note to add this to the list of features on the to-do list!

**Comment by thomason-jesse** [comment]
I noticed this didn't make it into 2.5.3. Any chance for it on a soon-ish commit?

**Comment by aishwaryap** [comment]
A related request. Would it possible to have an exposed method that converts an (x, y) on the egocentric image to an (x, y, z) in scene space using `raycast`. If we had this information, we could use a combination of `GetSpawnCoordinatesAboveReceptacle` and `PlaceObjectAtPoint` to perform the kind of placement requested in the main message. In addition, we can do things like find objects "near" rather than at the clicked location (helpful for small objects like pencils).

**Comment by thomason-jesse** [comment]
@winthos  I've put in a pull request that resolves this issue.
https://github.com/allenai/ai2thor/pull/627

**Comment by ekolve** [comment]
PR #684 resolves this issues.
