### ISSUE TITLE
`SinkBasin` not a valid receptacle anymore

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#541]
I noticed recently that the `SinkBasin` objects, at least in kitchen scenes, are no longer flagged as valid receptacles for `PutObject` actions. The error when selecting a `SinkBasin` for `PutObject` is "This target object is NOT a receptacle!"

**Comment by winthos** [comment]
could you provide which scenes you are finding this in so we can investigate further? Is it every kitchen? or just some?

**Comment by thomason-jesse** [comment]
I'm using the screenspace raycast. After playing over a few scenes it seems like SinkBasin can't be targeted with the (x, y) screenspace raycast.  I just checked out the first 6 kitchens and bathrooms by scene id.

Scenes where the action failed with "This target object is NOT a receptacle":
Kitchens: 1, 2, 5
Bathrooms: 2, 3

Scenes where the action results in the object going on the side/rim of the sink:
Kitchens: 3, 4, 6
Bathrooms: 1, 4, 6

Bathroom 5 looks like it sort of works?

**Comment by winthos** [comment]
My hunch right now is that the raycast targeting isn't fully compatible with sink basins. This is because that raycast goes out from a screen coordinate and tries to hit the colliders of a potential sim object target. sink basins actually don't have any collision, they are volumes of space that we define as an object for the purposes of distinguishing the body of the sink from the interior of the sink. Because of this, the default behavior of the screenspace cast might be missing these sort of targets. I will update this post as I investigate it further. 

One thing to try is if the screenspace targeting does not work, passing in the objectID of the sink basin directly should still allow objects to be placed in the basins, albeit in a more abstract manner.

**Comment by thomason-jesse** [comment]
Interesting. I had assumed the (x, y) was using the object segmentation masks. I can go back to using those to calculate which object was being targeted, as in benchmarks like ALFRED.  What's the benefit of using a raycast over gold segmentation for (x, y)? Just speed?

**Comment by winthos** [comment]
Yes, speed as well as another option for targeting in a more realistic way. The screen space targeting was originally designed just for the PickUp action, however the logic was rolled out to the other actions as well.

**Comment by thomason-jesse** [comment]
Swapping back over to specifying `objectId` and the bug gets... weirder. At least with the a recent commit `[ee615af53ba9ea9eb679c9aa4fccc5013701037e](https://github.com/allenai/ai2thor/commit/ee615af53ba9ea9eb679c9aa4fccc5013701037e)` trying to put any object down in any scene results in failure messages like `Target openable Receptacle is CLOSED, can't place if target is not open!` (even for countertops, sink basins, floors), or `This target object is NOT a receptacle!`. So far I haven't found a way to put an object down in this commit using `objectId`. The raycast (x, y) still work though, just not for `SinkBasin` objects.

**Comment by ekolve** [comment]
I have updated the PutObject action on the Unity side to use the parameter name 'objectId' for the receptacle instead of the parameter 'receptacleObjectId' (771e6fc440c3de1556f4659e7904e622acf60573).  The documentation was inconsistent with the actual implementation.  I'm not sure if this is the actual cause of the issue you are seeing, but PutObject would not have ever worked unless you used receptacleObjectId as the param name.

**Comment by thomason-jesse** [comment]
Thanks, Eric! Changing the target specification param name from `objectId` to `receptacleObjectId` did the trick.
