### ISSUE TITLE
[Feature Request] `placeStationary` flag for `SetObjectPoses`

### ISSUE THREAD

**Issue by thomason-jesse** [allenai/ai2thor#619]
`SetObjectPoses` restores objects to specified positions, but if those positions are set via, for example, `InitialRandomSpawn` with `placeStationary=True`, then when restored to those stationary positions via `SetObjectPoses`, the objects will fall/roll via physics into new positions. 

This feature would allow high-integrity scene restoration by restoring objects to their non-physics-resolved positions.

**Comment by winthos** [comment]
This has been added as of [release 2.7.3](https://github.com/allenai/ai2thor/releases/tag/2.7.3)

This update includes the `placeStationary` flag that will freeze the kinematics of repositioned objects.

Additionally, `SetObjectPoses` itself has been updated to also allow repositioning of `Moveable` objects as well as `Pickupable` objects, since both of these types of objects could have changed position over a run. Note that, because unspecified objects are removed from the scene, you will now need to specify all `Moveable` and all `Pickupable` objects that you don't want to remove from the scene.

**Comment by thomason-jesse** [comment]
Awesome!
