### ISSUE TITLE
Is the Unity window supposed to show smooth transition animations as in demo video?

### ISSUE THREAD

**Issue by jpstyle** [allenai/ai2thor#636]
Hello, is it normal that actions do not show smooth transitions in the Unity window as demonstrated in the promotional video, but instead only show the final resulting frames? For example, I was expecting to see a smooth animation of fridge door opening when I OpenObject a fridge, but I observe the fridge door instantly 'teleports' to its final position. If this is the intended behavior, is there a way to observe continuous transitions that must be internally happening somewhere in the Unity engine?

**Comment by mattdeitke** [comment]
The Unity window is not supposed to show as smooth of animations as the videos show. This is expected.

We optimize the Python side significantly for speed so that we can execute hundreds/thousands of frames per second. This is a practical problem for training reinforcement learning agents, which often take on the order of millions of frames to converge to something sensible.

For visualization, I often find it useful to use python's imaging library, moviepy, or matplotlib. Here is a demo using each in Colab:
https://colab.research.google.com/drive/1hhOd9lHC8cwJEoDpSrRq6uU2g6CgZrfE?usp=sharing

In terms of observing continuous actions from Python, we often just make extremely small interpolations such that it looks "continuous". For instance, we might make rotations that are each 2 degrees for 45 frames, instead of a single 90 degree rotation over a 1 frame.

**Comment by jpstyle** [comment]
I see, thanks for the prompt answer!
