### ISSUE TITLE
Difference in perception of objects from different viewpoints

### ISSUE THREAD

**Issue by sashi2295** [allenai/ai2thor#638]
Hi,

When I move the agent around in a scene, I noticed that there is an observable difference in the sizes of the objects when they are viewed from different viewpoints. Here is an example:

![1](https://user-images.githubusercontent.com/26632957/109054531-42c5ab00-76de-11eb-9fce-8d6322fdf03f.png)
![2](https://user-images.githubusercontent.com/26632957/109054546-45c09b80-76de-11eb-8078-9b209322938f.png)

In the first image, the desk (the one in dark brown) looks like a long one that is not so wide. But in the second image, it is shorter and wider.

I could also observe this for other objects.

I just wanted to know if there is an explanation for this and if there is a way to fix it.

**Comment by winthos** [comment]
Hello!

This is simply a trick of perspective due to the aspect ratio of your image, as well as the FOV setting of the agent's camera.

By default, our FOV is set to 90, which allows the agent the ability to view more things around even if limited by a small camera space given something like a square aspect ratio.

This is what you are seeing, at 90 FOV, objects might look like they get warped from different perspectives, even if they are the same object. Take a look at this example of the exact same shot but from different FOV settings:

60 FOV
![60](https://user-images.githubusercontent.com/17502636/109057427-91e7ed80-7696-11eb-8cae-d0d55bac3147.png)


90 FOV (default)
![90](https://user-images.githubusercontent.com/17502636/109057409-8ac0df80-7696-11eb-97c5-e43e883f1bbd.png)

120 FOV
![120](https://user-images.githubusercontent.com/17502636/109057443-96aca180-7696-11eb-9b75-e435a83592ba.png)

The higher the FOV of the agent camera goes, the more of this "fisheye" lens effect is observed. In order to reduce this effect, I would recommend adjusting the FOV to 60 which will compress the total scope of things your agent can see, but will reduce the perspective warp.

**Comment by sashi2295** [comment]
Thank you for the response!

Changing the FOV and aspect ratio has indeed reduced this effect!
