### ISSUE TITLE
Changing state of objects in Unity Editor

### ISSUE THREAD

**Issue by sashi2295** [allenai/ai2thor#649]
Hi,

I am trying to change the states of objects in one of the scenes such that the change is persistent. I tried to do this by making changes to object properties in the Unity Editor. Specifically, in `FloorPlan201`, the default state of the `Laptop` is `open`. I am trying to change this to `closed`.

I tried the following:

1. Open `FloorPlan201` in Unity Editor and select the `Laptop` object.
2. In the `Can Open_Object (Script)` section, uncheck the `IsOpen` option and set `Current Open Percentage` to `0`.
3. Save the scene and build.

But the `Laptop` is still open when I open the scene using the Python API.

Can you help me out?

**Comment by sashi2295** [comment]
I am not sure if I am not getting a response because there is an issue with the same heading (#637) just a couple of issues below mine. 

So, just to clarify, in #637, although the heading mentions changing the state of objects in the Unity Editor, the solution provided can only be used to change the state using the Python API, which is temporary. 

I am looking for something more persistent. So, I want to change the object state in the Unity Editor and build the scenes with this change, so that the change is permanent.

Another way to do this would be to open the scene using the Python API, make changes and save it so that it can be used later. But, I see from #250 that this functionality is still in development. 

I have searched through many issues and could not find a solution. So, any help is appreciated!

**Comment by winthos** [comment]
Hello!

Changing objects from the Unity Editor so that, by default, they are in a different state or position can be a little different depending on the exact types of state changes available to objects. It would be an extremely long explanation to go over how to change the default states of all possible objects, so I will start with just the `Book` example you mentioned in your question.

The `IsOpen` and `openness` fields on the `CanOpen_Object` component only store the information of what state the book is in, so changing them do not actually allow you to change the default state of the object as you have found. To actually change the default state of the `Book`, it is a bit more involved of a process.

You will see that there are some arrays on the `CanOpen_Object` component organized under some categories. The ones too look for are `Moving Parts` under the `Moving Parts for this Object` heading, the `Open Positions` as well as `Closed Positions` under the `Animation Parameters` header, also the `Open Bounding Box` and `Closed Bounding Box` under `References for the Open or Closed Bounding Box for openable and pickupable objects` heading. Additionally, you will need to change the `isOpen` bool under the `State Information Bools` heading.

![canopen_object](https://user-images.githubusercontent.com/17502636/111357095-392cc480-8646-11eb-9e09-6f94dda8541f.png)


If you want to just open the book, you will effectively need to manipulate the `Book` object manually by doing what the script itself does when running the "open" action. For the `Book` in scene `FloorPlan201`, you will first need to find the book itself in the Heirarchy window, then find the child object of that book called `book_front_1`. This is the "moving part" that is referenced in the `Moving Parts` array. 

![book_front_1](https://user-images.githubusercontent.com/17502636/111357073-3336e380-8646-11eb-8e6c-0b4b644d771c.png)

From there, you can check what about this child game object changes by looking at the `Animation Parameters`. You will see that the `Open Positions` contains a single element with a Vector3 value of (0, 0, 180). This means that when this `Book` is in the `open` state, the `book_front_1` game object has its `Z Rotation` set to 180. To do this, select the `book_front_1` object and go to its `Transform` component that you can find in the `Inspector` window. Change the Z rotation to 180.

![rotation](https://user-images.githubusercontent.com/17502636/111357158-46e24a00-8646-11eb-8e18-80c6a96649fe.png)

One thing to note here is the `Current Openness` value. This is a float between 0 and 1 that represents the percent that the book is open. If the book is all the way open at 180 degrees rotation, it is at 1 `Current Openness`. If this book were only opened to `0.5 Current Openness` then you would need to multiply the `Open Positions` Vector 3 by whatever the openness was. So if you wanted to default the book to halfway open, you would instead change the Z rotation of the `book_front_1` object to (0, 0, 180) * 0.5, or (0, 0, 90). This `Current Openness` value is calculated at runtime, so you don't need to change it in the editor. You only need to change the moving part's transform accordingly.

Next, make sure to switch the `isOpen` bool to true. This should be true anytime the `Current Openness` value is to be nonzero.

![isOpenBool](https://user-images.githubusercontent.com/17502636/111357177-4e095800-8646-11eb-8dac-189a1c7c7f9d.png)

Finally, you will need to change the Object Oriented Bounding Box reference for the `SimObjectPhysics` component on the book. Click the element named `Open Bounding Box` and it should highlight `Bounding Box` child object in the editor's Heirarchy window. What you need to do now is find the `SimObjPhysics` component on the `Book` and find the header on that component called `non Axis-Aligned Box enclosing all colliders of this object` and find the field called `Bounding Box`. You need to click and drag the `Bounding Box` child object referenced in the `Open Bounding Box` element on the `CanOpen_Object` into the `Bounding Box` field on the `SimObjPhysics` component. This is because the object oriented bounding box for an open object is a different box than the closed one, since the open object has a bigger profile.

![boundingBoxReplacement](https://user-images.githubusercontent.com/17502636/111357200-55306600-8646-11eb-8c93-2c44b1c5048c.png)

The final state of the `SimObjPhysics` component should look like this after dragging in the new object reference

![boundingBoxReplacementDone](https://user-images.githubusercontent.com/17502636/111357264-65484580-8646-11eb-9d00-905a2932f858.png)

There are a few more notes if you would want to try changing the default "open" state for other objects. If you look in the `State Information Bools` header, you will see a dropdown called `Movement Type`. This movement type determines how the Vector3 values in the `Animation Parameters` section behave. If the movement is `Rotate` then the moving parts of this object will change their `Transform's` `Rotation` value when animating, while if the movement type is `Slide` instead the `Transform's` `Positions` value will instead be what changes.

So, you can see this process is a bit involved, which is why we recommend changing the state of objects as part of your initialization step via the Python Controller. If there are other types of things you might want to change, like repositioning objects or changing different object states like turning lights on and off, or slicing/breaking objects. Please let me know and I can break down those processes in more detail.

**Comment by sashi2295** [comment]
Thank you so much for the detailed response! That explanation must have taken quite a bit of time to write and I really appreciate you taking out the the time to do it! :)

This process is indeed very involved and I think I will stick with using the API to make the changes. 

I am sorry that you had to give such a detailed explanation only for me not to use it in the end :grimacing:
