### ISSUE TITLE
Can I change first-person view to third-person view in thor?

### ISSUE THREAD

**Issue by ElizabethDuo** [allenai/ai2thor#65]
I wonder that if there is a way to observe how the agent move from third-person view. Or can I get the trajectory of the agent?
Thanks for help!!

**Comment by ekolve** [comment]
Do you want to be able to observe the agent from a camera fixed in some position?  There are a couple issues with this, one is that the camera is currently fixed to the agent and adding a third-party camera is non-trivial at the moment.  The second issue is that the agent has no body in single-agent mode.  It would be possible to add boolean to give the agent a capsule body that could be observed.  

Are you interested in an overhead/birds-eye view of the scene so that you can debug the path the agent is taking?

**Comment by ElizabethDuo** [comment]
Yes I am interseted in an overhead view of the scene to have a clear look of the agent's trajectory. And it would be better if the trajectory can be recorded.

**Comment by ekolve** [comment]
Support for third-party cameras has been added. 

This may satisfy your requirement:
```python
import ai2thor.controller
c = ai2thor.controller.Controller()
c.start()
c.reset('FloorPlan28') # any scene is fine
event = c.step(dict(action='AddThirdPartyCamera', rotation=dict(x=0, y=0, z=90), position=dict(x=-1.0, z=-2.0, y=1.0)))
event.third_party_camera_frames # list equal to number of third party cameras; each element is the image in numpy identical in shape to the agent's camera image

event.metadata['thirdPartyCameras'] # contains metadata about position/rotation of each camera
```

**Comment by ElizabethDuo** [comment]
I really appreciate your work! Thanks a lot!
I will try the new function!

**Comment by ElizabethDuo** [comment]
One more question, how to give the agent a body to visualize it in single agent mode?

**Comment by edugm94** [comment]
Hi all!

@ekolve , I have tried to run your code above, but I can not visualize the whole scene. If I set big numbers in y (in position dict)component (like 3.0), I obtain a wrong frame. How can I do in order to obtain the whole image from a roof top centered point of view of the scene?

Thanks in advance! :)

**Comment by ekolve** [comment]
@edugm94  Please see #124 for how to get a top down view.  Closing this issue as it appears to be resolved.
