### ISSUE TITLE
ai2thor with singularity

### ISSUE THREAD

**Issue by Gabesarch** [allenai/ai2thor#686]
Hello,

I am wondering if anyone would know how to run ai2thor headless through a [singularity](https://singularity.lbl.gov/docs-build-container) container. I have been at this for a few days now and any help would be greatly appreciated.

Thank you.

**Comment by ekolve** [comment]
Do you have a Xorg server already running on the host and can the `DISPLAY` be passed to the singularity container?

**Comment by Gabesarch** [comment]
Hi @ekolve,

I wasn't able get it working with xorg since I do not have root access and I couldn't find a way around this without root.

I managed to get it working by running with `xvfb` in the container similar to suggested in #105. However, as others were experiencing in that ticket, I am getting back all 0s from event.frame. Has there been a resolution to the event.frame issue that wouldn't involve docker or root access? 

I really appreciate the help.

**Comment by ekolve** [comment]
You can get Xvfb working by following the instructions in this comment:
https://github.com/Unity-Technologies/ml-agents/issues/1786#issuecomment-551280552

It will however not be suitable for training a model as the performance is extremely slow (< 10 FPS).  Root access is required in order to start a Xorg server unfortunately.

**Comment by Gabesarch** [comment]
Ok thank you for the help!
