### ISSUE TITLE
read in numerical input

### ISSUE THREAD

**Issue by he727425209** [allenai/ai2thor#72]
Hi,

I would like the microwave to read in a numerical input (time in seconds). Is there a way to do that in unity? I searched up and they are mostly related to keyboard input.

Best

**Comment by winthos** [comment]
Getting a Microwave object to read in a time parameter is a brand new feature request that currently does not exist in the Thor environment. Because this would be an entirely new feature it is not currently on the top of our priority list, however we will work to implement it in the future.

It is possible to implement this yourself in Unity by creating a custom microwave script that will accept a time parameter. Depending on what you want to do exactly you can read in inputs from a text input field and pass that into the Microwave function, or use the <ServerAction> class that most of our Agent’s actions receive parameters from.

Check this for more information about text input:
https://docs.unity3d.com/Manual/script-InputField.html

Input fields read in values as strings by default, so if you wanted to convert a string input into a number, you could do something like float.Parse(<string>).
