### ISSUE TITLE
Unexpected position after PutObject when forceAction=True

### ISSUE THREAD

**Issue by guhur** [allenai/ai2thor#800]
Hi,

The action PutObject is leading towards unexpected results when the argument forceAction is set as True:

```python
controller = Controller()
controller.reset("FloorPlan10")

object_id = "Apple|-00.66|+00.97|+00.07"
event = controller.step(action='PickupObject', objectId=object_id, forceAction=True)    

recept_id = "CounterTop|+00.93|+00.95|-00.21"
event = controller.step("PutObject", objectId=recept_id, forceAction=True, placeStationary=True)
```

Frame from the last event:
![image](https://user-images.githubusercontent.com/12297742/122774980-f7956080-d2a9-11eb-98ca-97a906678d68.png)

Actually, the apple is set behind the toaster, and I don't see why. Was the apple throw with maximum force?

![image](https://user-images.githubusercontent.com/12297742/122775110-18f64c80-d2aa-11eb-8b95-931578d69b7e.png)

However, with the following code, the apple location is in front of the agent, and is visible, as I would expect the action PutObject to work.

```python
...
event = controller.step("PutObject", objectId=recept_id, forceAction=False, placeStationary=True)
```

![image](https://user-images.githubusercontent.com/12297742/122774555-92416f80-d2a9-11eb-93c3-ec0e081493f4.png)

I don't know if this is a bug or a feature, but in the latter case, I think more details on how `forceAction` exactly works should be provided in the documentation.

**Comment by winthos** [comment]
Hello! What you are observing is the intended behavior, although we will be updating the documentation to make what you are seeing better explained.

The `forceAction` parameter does two things for the `PutObject` action. 

- Allows an object to be placed in any receptacle [regardless of "Default Compatible Receptacles" noted here.](https://ai2thor.allenai.org/ithor/documentation/objects/object-types)
- Removes the "visibility" range requirement from the action.

The default value with `forceAction=False` means the object placement is restricted to an area of the receptacle that is within the view of the agent's current camera aperture. This is why your second image with `forceAction=False` set restricts the apple to a position that the agent can see.

Your first image with `forceAction=True` (which I assume is what generated the image, as your example code shows `forceAction=False` while your description right before it indicates it was `True`?) means the Apple can be placed at any free position on that entire countertop regardless of if it is within the view. Nothing is changing with throw force or anything like that, its simply finding a free position on the countertop that is outside of the agent camera.

I believe some additional functionality built in to the `PutObject` action may help you position the `Apple` in a more accurate way based on what it appears you are trying to do. Instead of targeting a receptacle to place the `Apple` via the receptacle's `objectId`, you can instead pass in screen coordinates and use the `putNearXY` flag as follows:

```
controller.step(
    action="PutObject",
    x=0.64,
    y=0.40,
    forceAction=False,
    putNearXY=True,
    placeStationary=True
)

**Comment by guhur** [comment]
Thanks for your helpful message!

The first images were indeed generated with `firstAction=True`. I updated my question above. 

I think a warning could be added in the documentation. It sounds fair to assume that `forceAction=True` would first attempt in putting the object within the agent visibility, while it could arrive on any free position.
