### ISSUE TITLE
Shortest path behavior unexpected

### ISSUE THREAD

**Issue by zkytony** [allenai/ai2thor#825]
I hope to compute SPL using the shortest path towards some target, and it is convenient that ai2thor provides this function under `ai2thor.util.metrics.get_shortest_path_to_object_type`. 
However, the way it works is a bit unexpected to me. Here is a piece of code that obtains and plots the shortest path, on top of the grid of reachable positions. The version I'm using is 3.3.4.

```python
import matplotlib.pyplot as plt
import ai2thor.util.metrics as metrics
from ai2thor.controller import Controller
from pprint import pprint

controller = Controller(scene="FloorPlan1")

fig, ax = plt.subplots()

# plot the reachable loactions
event = controller.step(action="GetReachablePositions")
positions = event.metadata["actionReturn"]
x = [p['x'] for p in positions]
z = [p['z'] for p in positions]
ax.scatter(x, z)

# plot the shortest path to some object
metadata = controller.step(action="Pass").metadata
shortest_path = metrics.get_shortest_path_to_object_type(
    controller, "PepperShaker",
    initial_position=metadata["agent"]["position"],
    initial_rotation=metadata["agent"]["rotation"])
pprint(shortest_path)
px = [p["x"] for p in shortest_path]
pz = [p["z"] for p in shortest_path]
ax.plot(px, pz, "-o", c="orange")
ax.set_aspect("equal")
plt.show()
```
The plot looks like:
![Selection_334](https://user-images.githubusercontent.com/7720184/126381772-d2675541-4af3-46d1-84eb-7efb928cb1ce.png)

I was expecting the path would lie on the grids and each segment of the path is from one point to the grid to a neighbor point.
Because no agent will be able to produce the path as shown (it will always be longer than this), I worry if I should use it as the shortest path for computing the SPL metric.

Is there an explanation for this behavior, if it is reasonable? Should It be directly used to compute SPL?

Thanks!

**Comment by mattdeitke** [comment]
@zkytony completely agree that this is unexpected behavior. It was also really unexpected to me as well.

It is still in place because of technical debt, and to report fair more comparable baselines with older projects that used reported SPL using this definition of shortest path.

Here is some old code I shared with somebody to compute the shortest path from the reachable grid positions, which would solve the of SPL points not being on the grid:
https://colab.research.google.com/drive/1uw7SmxUnLwn3Y6HcqqvEhHnyRJ0Jv8kb?usp=sharing

I suspect the SPL number won't be all that different based on which path length definition is used, but I think it should be updated at some point to only use points on the grid by default.

**Comment by zkytony** [comment]
Thanks for the information! I'll use the grid points then. I agree that it will probably not be that different in terms of comparison between different methods.

**Comment by Tangolin** [comment]
@mattdeitke seem to me that the code will still consider 2 points as neighbours even if there are some form of obstruction(e.g. wall) so long as they are less than 1.5*grid distance apart? am I right to say that?
