### ISSUE TITLE
Get literally visible objects in the agent's view

### ISSUE THREAD

**Issue by 594zyc** [allenai/ai2thor#854]
Hi,

Thanks for all the great work you have been done! After playing with iTHOR for some time, I just wonder if there is a convenient way to check whether an object can be seen in the agent's egocentric view, regardless of the visibilityDistance constraint. I want to do this because I want to distinguish the objects that are literally "visible" and are "interactable" (indicated by the existing `visible` property). 

Although I have figured out some implementation solutions such as getting the information from the segmentation meta or setting the "visibilityDistance" to a large number and using another distance threshold for computing the intractability, both of them slow down the program. Do you have any idea of a better implementation of this? 

Thank you very much!

**Comment by mattdeitke** [comment]
Hi @594zyc. I would personally recommend the solution you mentioned of setting `visibilityDistance` to some larger number (e.g., 20) upon initialization.

It would surprise me that it slows the program down, since (I think) all visibility points are typically checked at each time step, independent of the `visibilityDistance`.

You may find https://github.com/allenai/ai2thor/issues/815 useful for describing why visibility is faster than segmentation.

**Comment by 594zyc** [comment]
Hi @mattdeitke , thanks so much for the quick response! Helps a lot!
