### ISSUE TITLE
Checking if object can be placed on a receptacle

### ISSUE THREAD

**Issue by qazwini** [allenai/ai2thor#896]
I needed a way of inferring if an object could be placed on a receptacle before placing it. Because that is dynamically determined based on the size of the object and receptacle and the remaining space left on the receptacle, I limited each receptacle to be able to contain one object. There is still an error I'm getting. Sometimes I still get the "No valid positions to place object found" error (like when placing DishSponge on empty Cabinet), even though there are no other objects on the receptacle. I suspect that the object alone is still too large to fit on the receptacle. Is there a solution to this, or should I test out every combination and hard code it?

**Comment by winthos** [comment]
I assume you are using the [PutObject](https://ai2thor.allenai.org/ithor/documentation/interactive-physics/#sub-put-object) action when attempting to place things in your empty receptacles. It is likely that even if the receptacle is completely free of other objects, the valid area in/on that receptacle may be too small for other objects to be placed. 

The internal logic of the `PutObject` action has a built in check to see if an object can fit in/on a receptacle. The receptacle object generates a number of potential spawn positions, and each position is checked to see if the object to be placed will fit. Unfortunately, there is not a singular action that will report back if an object can contain another object, as this is built into the `PutObject` action itself. The most straightforward way to handle this would be to try out various combinations and record the success as the action itself fails or succeeds. However, there may be a few other options to help expedite this process and get you to your end goal.

A few things I would try first would be passing in `forceAction=True` as a parameter of `PutObject`. Without this behavior, there are certain agent camera centric checks that are done that may result in the "no valid positions..." error message. Also in regards to this, you can try moving the agent so that its camera can fully see the entirety of the receptacle in question. Certain receptacles will have limited areas of placement if some part of the receptacle is not within the agent viewport, so this could be a source of restricted positions even though the object is empty.

To get a better understanding of what is going on, could you post a code snippet or a sequence of actions that gives you an error message? We can look into it to see if there is some sort of error in the `PutObject` logic, as the action itself is complex due to the dynamically generated nature of it, so it is hard to figure out exactly what is wrong without a reproducible example case.

Another thing to try would be using some combination of the [Get Spawn Coordinates Above Receptacle](https://ai2thor.allenai.org/ithor/documentation/interactive-physics/#sub-get-spawn-coordinate-above-receptacle) action and the [Place Object at Point](https://ai2thor.allenai.org/ithor/documentation/interactive-physics/#sub-place-object-at-point) action. These two actions work slightly differently from the internal logic of `PutObject`. Namely, `GetSpawnCoordinatesAboveReceptacle` will return the potential spawn coordinates that are above the surface of a target receptacle. When passing in one of these points to `PlaceObjectAtPoint`, what happens is a ray is cast straight down from that point above the receptacle down toward the receptacle surface. The point of contact on the surface of the receptacle is then used to try and place a given object at that point of contact. This is slightly different from the `PutObject` action as it is less abstract, and will potentially offer more fine tuned control over where you want to place an object. Because it is less abstract, it will require more input to get a valid placement, but will likely fail less compared to using just `PutObject`.

**Comment by qazwini** [comment]
Thanks! I just ended up making a custom compatibility list by testing which objects always can go on which receptacle.
