### ISSUE TITLE
Object failed to open/close successfully. Cause?

### ISSUE THREAD

**Issue by qazwini** [allenai/ai2thor#904]
Is there a way to determine if an object will fail to open for some reason, prior to calling the action? I just check to see if the object is `openable` and it's also either not `isOpen` or the `openness` is less than 1. In general, this seems to work. However, I came across this error message when trying to open the fridge (`Fridge_683c888d`) in floor plan 5 with the `OpenObject` action and with `forceAction` on: "Object failed to open/close successfully." I'm not really sure why I am getting this error. Is there a common reason why the action would fail and give this error message? And is there a way to tell if this action will fail before calling it?

**Comment by winthos** [comment]
Could you give a code snipped to reproduce this scene state? It could be the agent is in the way of the fridge door, which would cause it to fail if it were to try and open into the agent's colliders and clip with the agent.

**Comment by qazwini** [comment]
Sure! I'll send steps to reproduce this issue as soon as I come across it again.

**Comment by qazwini** [comment]
Also happens with `Cabinet`.

**Comment by winthos** [comment]
It seems that you are leaving the agent in its default starting position in Floor Plan 5, and because of this, the angle of the Fridge opening is hitting the agent's collision. This is why the Fridge is failing to open, at least. Here is a top down view of what is happening in that scene when I try and open the fridge given the agent at the position you posted.


![OpenFridge](https://user-images.githubusercontent.com/17502636/136851084-76ab273f-cf1a-4d44-bf64-2eb937a8aabc.gif)


You can try and open the fridge using a smaller opening percentage, like only 70% open to ensure the fridge door doesn't hit the agent. You can [look at the `openness` parameter](https://ai2thor.allenai.org/ithor/documentation/object-state-changes/#OpenObject-openness) to only partially open an object.

I'm not sure what is happening with the Cabinets. Is it a specific cabinet that isn't opening, or is it failing to open no matter which cabinet you try to open?

Can you give the exact code snippet to reproduce this issue with cabinets? I would need more than the metadata after the action, I'd also need things like your [`Initialize` parameters](https://ai2thor.allenai.org/ithor/documentation/initialization/#initialization) and any actions taken before the actual `OpenObject` action happens, such as moving the agent or teleporting the agent into a different position.

Most likely, it's either the agent or some other object, like a chair or a stool, that may be in the way of the cabinet opening and causing it to fail.

**Comment by qazwini** [comment]
Oh, that makes much more sense. I think the cabinet issue was also the same. Thank you very much!
