### ISSUE TITLE
After Slicing Cloned Bread, Slices Behave Like Bread

### ISSUE THREAD

**Issue by qazwini** [allenai/ai2thor#908]
After I slice an object of type `Bread`, the resulting slices have type `BreadSliced`. The same happens with all other sliceable objects. However, duplicate `Bread` objects do not behave like that. I am using the `InitialRandomSpawn` action to create three duplicates of `Bread` and `Apple` and a few others.
```python
controller.step(
    action = "InitialRandomSpawn",
    randomSeed = seed,
    forceVisible = False,
    numPlacementAttempts = 5,
    placeStationary = True,
    numDuplicatesOfType = [
        {
            "objectType": "Bread",
            "count": 3,
        },
        {
            "objectType": "Apple",
            "count": 3,
        },
        # More duplicates...
    ]
)
```
The behavior of all the cloned objects seems to be perfectly normal, just like the actual object, except for `Bread` clones. When I slice them using `SliceObject`, they get sliced, and their name changes to `Bread_X_Slice_Y`, but other parts of the metadata are incorrect. Rather than behaving like sliced bread, they behave like bread. Their `objectType` is `Bread` rather than `BreadSliced` and they're also not `cookable`. The original `Bread` object that does not have the "(clone)" in its name behaves properly when sliced, but in every environment, there is an issue with `Bread` clones. `Apple` clones and other clones behave exactly as expected.

Here is the metadata for one of the cloned object slices:
```
{'name': 'Bread_28_Slice_2', 'position': {'x': -1.578650712966919, 'y': 0.07124952226877213, 'z': -2.5389435291290283}, 'rotation': {'x': 0.020067069679498672, 'y': -0.00012221571523696184, 'z': -0.004641969688236713}, 'visible': False, 'obstructed': True, 'receptacle': False, 'toggleable': False, 'isToggled': False, 'breakable': False, 'isBroken': False, 'canFillWithLiquid': False, 'isFilledWithLiquid': False, 'fillLiquid': None, 'dirtyable': False, 'isDirty': False, 'canBeUsedUp': False, 'isUsedUp': False, 'cookable': True, 'isCooked': False, 'temperature': 'RoomTemp', 'isHeatSource': False, 'isColdSource': False, 'sliceable': False, 'isSliced': False, 'openable': False, 'isOpen': False, 'openness': 0.0, 'pickupable': True, 'isPickedUp': False, 'moveable': False, 'mass': 0.057100001722574234, 'salientMaterials': ['Food'], 'receptacleObjectIds': None, 'distance': 1.331943154335022, 'objectType': 'BreadSliced', 'objectId': 'Bread|-00.32|+01.56|-00.65|BreadSliced_1', 'parentReceptacles': ['Floor|+00.00|+00.00|+00.00'], 'controlledObjects': None, 'isMoving': False, 'axisAlignedBoundingBox': {'cornerPoints': [[-1.508042812347412, 0.1422290951013565, -2.5239973068237305], [-1.508042812347412, 0.1422290951013565, -2.553892135620117], [-1.508042812347412, -1.2233853340148926e-05, -2.5239973068237305], [-1.508042812347412, -1.2233853340148926e-05, -2.553892135620117], [-1.6478607654571533, 0.1422290951013565, -2.5239973068237305], [-1.6478607654571533, 0.1422290951013565, -2.553892135620117], [-1.6478607654571533, -1.2233853340148926e-05, -2.5239973068237305], [-1.6478607654571533, -1.2233853340148926e-05, -2.553892135620117]], 'center': {'x': -1.5779517889022827, 'y': 0.07110843062400818, 'z': -2.538944721221924}, 'size': {'x': 0.1398179531097412, 'y': 0.14224132895469666, 'z': 0.02989482879638672}}, 'objectOrientedBoundingBox': {'cornerPoints': [[-1.5080523490905762, -1.2218952178955078e-05, -2.524047613143921], [-1.6478607654571533, -7.972121238708496e-07, -2.5240478515625], [-1.6478607654571533, 9.782612323760986e-06, -2.5538923740386963], [-1.5080523490905762, -1.6391277313232422e-06, -2.553892135620117], [-1.5080406665802002, 0.14220958948135376, -2.5239973068237305], [-1.6478490829467773, 0.14222100377082825, -2.5239973068237305], [-1.6478490829467773, 0.14223158359527588, -2.5538418292999268], [-1.5080406665802002, 0.1422201693058014, -2.5538418292999268]]}}
```

**Comment by winthos** [comment]
I think your issue may be something related to mismatching the `objectId` or the `name` you are getting for the cloned object slices in the metadata.

Based on your metadata, everything looks correct. From the metadata for the cloned object slice you provided, the `objectType` and `cookable` state look as expected.

I've copied and pasted these specific parts directly from your provided metadata:
```
'name': 'Bread_28_Slice_2'
'objectId': 'Bread|-00.32|+01.56|-00.65|BreadSliced_1'
'objectType': 'BreadSliced'
'cookable': True 
'isCooked': False
```
So this does appear to be a `BreadSliced` object type, not a `Bread` object type, and it is also `cookable = True` as expected.

Notably, after a `Bread` object is sliced into `BreadSliced` the `objectId` of the sliced bread will inherit the `objectId` of the original `Bread` that it came from. The `objectId` should be the unique identifier for that particular bread slice. So this particular object named `Bread_28_Slice_2` has the id `Bread|-00.32|+01.56|-00.65|BreadSliced_1`. This means that this bread slice came from the `Bread` object in the scene with the `objectId` of `Bread|-00.32|+01.56|-00.65`.

The object `name` is not guaranteed to be completely unique when cloning objects via `InitialRandomSpawn` because even though the original Bread and the Bread (clone) created during Random Spawn have different `name` fields, they both are the from the same source object and therefore will spawn the same bread slices.

**Comment by winthos** [comment]
I see, I will check a few things on our end to see if we can get to the bottom of this. Could you provide a few more details like which version of THOR you are using, as well as which scene you are in? Your original code snipped doesn't specify these things and I'd need them to more accurately try and recreate your results.

**Comment by qazwini** [comment]
Ohhhh. I just tested and that does seem to be the case. Thank you so much for your help!
