### ISSUE TITLE
Opened objects block agent movements

### ISSUE THREAD

**Issue by LeonardoL96** [allenai/ai2thor#948]
Hello everyone,

I have a doubt about collisions with opened objects in ai2thor 4.0.0.

In FloorPlan30, after opening a cabinet, the agent seems no more able to move. I think this is no expected behaviour, but maybe I'm missing something.

To reproduce the issue (in ai2thor 4.0.0) 

```    
from ai2thor.controller import Controller

c = Controller(scene='FloorPlan30', fieldOfView=79, width=224, height=224)

c.step(action="TeleportFull",
       position={'x': 2.5, 'y': 0.9277887344360352, 'z': -1.25},
       rotation={'x': -0.0, 'y': 90.0, 'z': 0.0},
       horizon=0,
       standing=True)
```

Print the instance name of the cabinet 
``` 
cabinet_id = c.step('GetObjectInFrame', x=.5, y=.5).metadata['actionReturn']
cabinet_name = [o for o in c.last_event.metadata['objects'] if o['objectId'] == cabinet_id][0]['name']
print(cabinet_name)
```
The code above returns `Cabinet_e8c521bb`
```
c.step(action='OpenObject', x=0.5, y=0.5)

c.step('RotateRight')
c.step('MoveAhead')
print(c.last_event.metadata['errorMessage'])
```
The code above returns `Cabinet_e8c521bb is blocking Agent 0 from moving by (0.0000, 0.0000, -0.2500).`
```
c.step('RotateRight')
c.step('MoveAhead')
print(c.last_event.metadata['errorMessage'])
```
Still returns `Cabinet_e8c521bb is blocking Agent 0 from moving by (-0.2500, 0.0000, 0.0000).`

Thank you, 
Leonardo

**Comment by winthos** [comment]
Hello!

Yes, given this exact configuration of where the agent is and how the cabinet is opened, this is expected behavior. What is happening is the Agent's collision is clipping inside of the open cabinet door very slightly, which is causing the agent to get stuck and not be able to move. When opening objects, agent collision is temporarily disabled during the opening animation in order to allow the agent to manipulate things like a cabinet or a drawer in potentially cramped areas like in between counters of a kitchen. In this case, the agent is standing so close to the cabinet that when the cabinet is fully open, the cabinet geometry is slightly overlapping with the agent. You can see this here:

![InkedCabinetClipsWithAgent_LI](https://user-images.githubusercontent.com/17502636/145099759-268c9848-3172-4a58-bbda-c1e003f65476.jpg)

In order to prevent this, I would just teleport the agent slightly to the right to something like (2.5, 0.927, -1.5) as its position rather than the z value being -1.25

**Comment by LeonardoL96** [comment]
Thanks a lot for the reply. I think I got your point and I see this behaviour as a kind of trade-off to allow manipulation in cramped areas. Maybe it could be useful to either prevent the successful execution of the action when the manipulated object overlaps with the agent or add an attribute which indicates whether the agent got stuck in these cases.

Thank you, 
Leonardo
