### ISSUE TITLE
Some objects' parentReceptacles is None

### ISSUE THREAD

**Issue by LWJ312** [allenai/ai2thor#965]
Excuse me, I found that several objects' **parentReceptacles is None** after initialization. 
The ai2thor's version is 4.0.0
Some reasons may be that the parentReceptacles belong to the room's structures. But other cases referring to SimOjects also return None parentReceptacles.
For example (actually, this happens in many scenes), in FloorPlan219, the _Box|-02.31|+00.72|+00.35_  outputs **None parentReceptacles,** while it is on the safe.
In FloorPlan309, both the _CreditCard|-02.33|+01.10|-02.82_ and _Pen|-01.38|+01.11|-03.05_ are on the _Desk|-01.27|+01.17|-02.99_, but the CreditCard's parentReceptacles is **None**, while the Pen's parentReceptacles returns the Desk.

**Comment by winthos** [comment]
Hello! Thank you for bringing this to our attention. The issue with the credit card object in FloorPlan309 was due to a offset placement of the desk's "`Receptacle Trigger Box`" which is just a volume of space used to define the area of an object that is considered a receptacle. Our internal logic reports back an object's parentReceptacle if the object's own collision intersects with the `Receptacle Trigger Box` of a receptacle object. You can visualize the desks' receptacle box in the following image taken from the Unity editor.

![Screenshot 2022-01-05 115014](https://user-images.githubusercontent.com/17502636/148280584-b5bd4dd3-244f-4d90-9a38-e4292f628e2f.jpg)

You can see here from a side view that the desk's receptacle box was slightly offset to be too high off the surface of the desk by a few millimeters, which caused the credit card, one of our thinnest objects, to fail to be detected. I've fixed the positioning of this desk's trigger box which will be live in the next release.

![Screenshot 2022-01-05 115050](https://user-images.githubusercontent.com/17502636/148280599-3fac59aa-ea00-4c24-81d8-6b1b165ef7b8.jpg)

As far as the `Safe` object goes, this is working as intended. The safe's receptacle area is defined only as the interior of the safe, not the top of it. The box in FloorPlan219 rests on top of the safe, but because the safe can only detect objects inside of it as contained, the box would not report its parentReceptacle as the safe unless the box was inside the safe. You can see here that the safe's `Receptacle Trigger Box` is only defined for the interior of the safe. 

![Screenshot 2022-01-05 114838](https://user-images.githubusercontent.com/17502636/148280930-d0c995ba-d55d-46c8-b35e-21226ccfb774.jpg)

This may seem a bit inconsistent, but because the `Safe` object can often be placed inside nooks and crannies in various scenes, it is not always guaranteed that the top part of the safe is open and free for objects to be set on top of it. Because the same safe asset is used across many scenes, it was decided to only allow the safe's interior to be used as a receptacle area.

**Comment by LWJ312** [comment]
Get it! Thanks for your detailed explanation. It helps a lot ~

**Comment by winthos** [comment]
As an update, this desk collider has been fixed as of [release 4.1.0](https://github.com/allenai/ai2thor/releases/tag/4.1.0) which is now live.
